### ISSUE TITLE
Enhancement Request - http input - provide additional meta data

### ISSUE THREAD

**Issue by ryn9** [benthosdev/benthos#1052]
**Enhancement Request**

It would be beneficial for Benthos to provide additional network and tls meta data for the http input (and perhaps other network inputs).

This would be like Logstash provides for some sources.
For example - using Logtash's beats input, the user then can make use of the following provided variables:
@metadata.ip_address
@metadata.tls_peer.status
@metadata.tls_peer.protocol
@metadata.tls_peer.subject
@metadata.tls_peer.cipher_suite

References
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html#plugins-inputs-beats-ecs_metadata

**Comment by isae** [comment]
@Jeffail can I implement this? I need the remote ip address for my Benthos use-case, but I could add TLS information to meta as well.
