### ISSUE TITLE
Feature: Use resource labels as references in unit tests, instead of JSON pointers

### ISSUE THREAD

**Issue by EmilLaursen** [benthosdev/benthos#1057]
Using JSON pointers to reference a `target_processor` for testing has some drawbacks. The JSON pointer must include the `index` of the resource, e.g.
```yaml
    target_processors: './my_resources.yaml#/processor_resources/1'
```
As a consequence, adding/removing processors to the resource file, or refactoring the order, must be reflected in the JSON pointers in each test.

A natural alternative would be using the resource label. This has a few benefits over JSON pointers

1) Consistent with the existing API for referencing resources in configs
2) Immune to modifications of a resource file as described above

A possible API (suggested by @Jeffail ) is adding an alternative `target_resource` along side `target_processor` in the test file spec. An example could be
```yaml
 target_resource: './my_resources.yaml#/processor_resources/my_processor_label'
```
However, I am sure you are better at figuring out an API than I am.

**Comment by boorad** [comment]
If this is implemented, could we do something like

```yaml
target_processors:
  - resource: first_processor_label
  - resource: second_processor_label
```
which would allow testing of multiple processors but not the entire pipeline?

**Comment by Jeffail** [comment]
Hey @boorad, I think that'd be the goal, initially I'll probably add support for a single resource by label, so it'd look like `target_processors: foo` or `target_processors: ./my_resources.yaml#foo`, but we can maybe expand the field to support a list later on.

**Comment by boorad** [comment]
Sounds good.  I like the `- resource: {label}` form because it would give you the flexibility to put an actual processor in there.  I'm not sure if it's a best practice to have a processor in your test pipeline that's not in your actual one, but maybe we could view that as a more aggressive form of mocking :)

**Comment by Jeffail** [comment]
done in a basic form here: https://github.com/benthosdev/benthos/commit/7f9e3a2eb7dbb5a218a915d385412b9cda4c23ac, I'm closing as we have a solution, but there's room in future to expand or modify the unit test schema if we want a better fit.
