### ISSUE TITLE
Benthos V4 Implementation Plan

### ISSUE THREAD

**Issue by Jeffail** [benthosdev/benthos#1071]
# V4 Implementation Plan

Now that the majority of V4 functionality is implemented (new plugin APIs, templating, etc) we can finally begin the work of cutting a V4 release. This process is not one of adding features but of removing old and deprecated ones, with the end goal of freeing us of burdens that are currently preventing (or hindering) efforts to improve the service further.

The main risk with cutting V4 is that for a period of time we will have two hot branches, one containing our V4 work while it's in progress, and one providing features and fixes for V3 users in the meantime. Ideally we want to minimize this period of time by getting the first stable release of V4 out as soon as possible, and this way we can cool down the V3 work to only focus on back-porting fixes for occasional patch releases.

A huge amount of effort has already gone into this by implementing V4 features in a backwards compatible way so that they're available and tested within V3 releases. This should also hopefully relieve a lot of the burden of migrations for users, as they've able to gradually adopt V4 functionality in increments.

However, for this final stretch of work there are a few issues remaining that will need implementing during the cut (anything marked as blocked: https://github.com/Jeffail/benthos/projects/2) as they involve breaking changes. Therefore in order to make this transition as smooth as possible we're going to do it in the following phases.

## Phase 1 - Delete

We begin our journey by creating a new branch off `master` called `v4`. The purpose of `master` will remain the same (all features, bug fixes and releases). On the `v4` branch we will delete every single deprecated component, field, and API. During this time our diffs should be mostly red with a few exceptions, and it is important that nothing is moved as this will make it more difficult to keep this branch up to date with `master`.

Once we have all deprecated features removed from `v4` it will make any future refactoring smoother.

We will also need to create a new migration section in the documentation that we will keep up to date with our changes, at this stage we will simply need to list the things we're deleting. If the list of deprecated components is unreasonably long then we can reconsider whether they need to explicitly listed at all.

## Phase 2 - Change

Once we're finished with deletions we can move onto adding new functionality, all of the blocked items on the V4 board: https://github.com/Jeffail/benthos/projects/2 can be worked on. Ideally we would want to minimize the fingerprint of these diffs in order to help keep us in sync with `master`.

Each issue will require a separate entry within the migration guides in the docs. For large impact ones like the metrics changes this could even be an entire page.

## Phase 3 - Move

Once the main body of breaking changes are done the last requirement is to hide all of the old packages from `lib`. Ideally we will eventually find new homes for all of this functionality in more appropriate locations. However, in the interest of minimizing risk it is enough to simply hide the entire package into something like `internal/old`, which minimizes the diff into just renaming paths.

When we're renaming package paths we should also rename the module itself from `github.com/Jeffail/benthos/v3` to the new module `github.com/benthosdev/benthos/v4` as we're moving the repo into `benthosdev` when the release is cut.

## Phase 4 - Review

After this process we will need to wait for the next major version release before we can break things again, which will hopefully be way into the future. As such it's worth reviewing all components that are left, Bloblang, configuration formats, etc for breaking changes that could be made that would significantly improve them.

This should be a conservative effort as every breaking change we add increases the burden on users when they plan their upgrade. A small and seemingly insignificant break to you might translate to long hours of investigation for someone experiencing the break, so please keep this in mind when proposing changes.

## Phase 5 - Test

Once we're happy with what we have we need to test it to oblivion. Testing here isn't just important from a stability point of view but also from a usability point of view. If we've introduced a breaking change thinking it makes life easier but it turns out it's worse for users than what we had before then that's something we need to capture as soon as possible.

The number one priority of a breaking change is to make functionality more consistent, more seamless, and more intuitive. The absolute worst outcome is that we end up with something more complicated, let's not allow that to happen by making sure we have lots of testing time.

During this phase we will create a new `v3` branch from `master` which will contain all future V3 work (bug fixes) as we begin to cool V3 off. A new `main` branch will be created from `v4`, which we can retire as we make `main` the default branch. Finally, we move the project to the `benthosdev` organisation.

Hopefully by cooling off V3 we can encourage users to try out V4. We will start by asking users to try nightly builds but once we're more confident we'll start putting release candidates out.

## Phase 6 - Release

When we're happy with our V4 testing we can finally put a release out. We first need to ensure a full snapshot of the documentation site is hosted somewhere, maybe `v3.benthos.dev`. Then we can tag a proper release and update the `site` branch to the shiny new goodies.

**Comment by Jeffail** [comment]
Phase 1 in progress: https://github.com/Jeffail/benthos/tree/v4

For those interested I'm streaming most of the work here, first part is here: https://youtu.be/Ny9E0SAji0I

**Comment by luxixing** [comment]
Some of the libraries that benthos' go.mod file https://github.com/Jeffail/benthos/blob/v4/go.mod depends on are
cloud.google.com/*
github.com/Azure/* 

There may not be many scenarios where cloud services like this are used, so I would like to remove direct dependencies on these in go.mod and import them when needed. This would remove a lot of non-essential libraries and reduce the compiled version and memory footprint.

The use of plugins shouldn't be flexible for users to configure, and shouldn't integrate a lot of non-core plugins into the core of benthos

Translated with www.DeepL.com/Translator (free version)

**Comment by Jeffail** [comment]
@luxixing yep thats something we're working on, in V4 you'll be able to cherry-pick which groups of plugins you build into your binary.

**Comment by Jeffail** [comment]
Sorry, forgot to update this issue but we're well into phase 3 now, the package movements are done, just working up the courage to click move on the project repo (and some final touches on migration guide). Phase 4 coming soon.

**Comment by Jeffail** [comment]
Phase 3 done, 🥁 ENTERING PHASE 4 🥁

**Comment by Jeffail** [comment]
Into phase 5 now with a release candidate: https://github.com/benthosdev/benthos/releases/tag/v4.0.0-rc1, there will be more so there's still time for changes, make sure you get your feedback in.

**Comment by Jeffail** [comment]
V4 PROPER IS DONE, thank you to everyone that tested, gave feedback, contributed code, contributed emotional support and all the other junk. I'm leaving this issue pinned for now.

https://github.com/benthosdev/benthos/releases/tag/v4.0.0
