### ISSUE TITLE
sftp output processor giving issues when connecting to a managed services (Transfer Family Server) at AWS

### ISSUE THREAD

**Issue by DavidDattner-nbcuni** [benthosdev/benthos#1172]
When trying to SFTP output out aws managed service SFTP you get this issue with Benthos:

{"@timestamp":"2022-03-14T10:05:41-07:00","@service":"etl_uniroster","component":"uniroster.output","stream":"unirostercmt_conf","level":"ERROR","message":"Failed to send message to sftp: sftp: \"Cannot open file in mode: APPEND|CREATE|READ|WRITE\" (SSH_FX_OP_UNSUPPORTED)"}

Please help! Thanks, David.

**Comment by DavidDattner-nbcuni** [comment]
here's the fix info:
https://github.com/pkg/sftp/issues/305

**Comment by Jeffail** [comment]
Hmmm, not sure that's the issue as we're using a version released way after that fix: https://github.com/benthosdev/benthos/blob/fb2cdfd4969212d44923798489245d0a1b39a1b3/go.mod#L95

**Comment by Jeffail** [comment]
https://github.com/benthosdev/benthos/commit/dd42aa033d9cc7c4f705c82edb1c5cb6fca82005
