### ISSUE TITLE
Replace parquet implementation with segmentio/parquet-go

### ISSUE THREAD

**Issue by Jeffail** [benthosdev/benthos#1205]
Given all the issues we're seeing both in terms of functionality and the APIs themselves I'm fairly desperate to get away from the parquet library we're currently using. Luckily https://github.com/segmentio/parquet-go has appeared and seems to remedy every issue I had.

Since I can see light at the end of the parquet tunnel it'd be a massive shame to ship V4 with the existing janky processor taking up the name of `parquet`. However, the tricky part is that I don't think we can realistically investigate and replace the processor with this library before we conclude V4, and even if we could there would be a migration necessary as the existing processor has a gross and awkward config format due to the aforementioned issues.

I think that a good compromise might be to rename the existing `parquet` processor to a temporary name `xparquet`, which is marked as deprecated and "scheduled for removal" in V4. This processor will work exactly the same. Once we finish evaluating this new client library we can eventually add a proper `parquet` processor and have people gradually migrate to it.

Once we're confident users have had plenty of time to migrate we can remove `xparquet` and the dependencies it brought in.

So the migration process for an existing parquet user would be:
- Prepare configs generally for v4 migration
- Rename all `parquet` processors to `xparquet`, the config stays the same
- Deploy configs with v4
- Slowly migrate processors to `parquet` once it becomes available

Anyone have any concerns or thoughts around this? The entirety of this plan is flexible so I'm open to all ideas.

**Comment by FourSpaces** [comment]
@Jeffail  What are the evaluation requirements for new clients? I think I can help complete the evaluation and testing of the new parquet processor.

**Comment by Jeffail** [comment]
Ideally what I'd like is:
- No explicit schema necessary for consuming parquet files
- Better error messages for when data does not match a given schema for writing parquet files (or the schema is invalid)
- Better ability to read and write against arbitrary streams, this would enable us to have parquet codecs

I did some evaluation of the library and unfortunately I don't think it's quite there yet. I tried reading several parquet files (including some I created myself) and it couldn't read any of them. I haven't got time right now to dig into why so for now I'm going to cool off on renaming the existing `parquet` processor and we can revisit well into v4.

**Comment by achille-roussel** [comment]
Hello, 

I noticed your interest in segmentio/parquet-go and the issues you reported reading parquet files, I'd love to help resolve these. 

Would you be able to share the files that you had trouble reading? Or share the method you followed to generate them? These would be highly valuable to have to access to. 

I also wanted to mention that we have landed a few fixes recently that helped address issues where segmentio/parquet-go had trouble reading files generated by other libraries, maybe the problems you ran into may already be fixed. 


Cheers!

**Comment by Jeffail** [comment]
Hey @achille-roussel, will do. Not sure when I'll have time to revisit but hopefully soon I can put together a test suite of example schemas+files, if there's any issues at that point I'll open an issue on segmentio/parquet-go and share the problematic files.

**Comment by boorad** [comment]
As discussed with @mihaitodor in Discord, we have files in S3 that Flink wrote with [parquet-avro](https://javadoc.io/doc/org.apache.parquet/parquet-avro/latest/org/apache/parquet/avro/package-summary.html).  The existing parquet library does not read these files successfully, but segmentio/parquet-go does.  Another example of this lib remedying issues w/ existing lib.  See attached for small decoding script and example file.

[benthos-1205.zip](https://github.com/benthosdev/benthos/files/8634607/benthos-1205.zip)

**Comment by boorad** [comment]
I was able to get a custom processor to work with our schema and we are good to go.  However it's not general enough to help this issue here, as we hard-code our schema like the sample script above.

**Comment by Jeffail** [comment]
Hey @achille-roussel I'm back on this and getting good results when extracting schemas that contain only leaf values. However, I'm struggling to work out how I would go about extracting group values in a generic way, I've gotten as far as this: https://github.com/benthosdev/benthos/blob/segmentio-parquet/internal/impl/parquet/segmentio_library_test.go#L61

Specifically I have a reference to a `parquet.Field` that says it's a non-leaf node, and I have a `parquet.Value` that points to the data, but I can't see a way to walk the value. Is this something I'd need an explicit schema for up-front?

**Comment by Jeffail** [comment]
Okay I feel a bit more familiar with how the repetition and definition levels work so I think I should be able to create a generic row value walker. Hoping to have something usable within the next week or so.

**Comment by achille-roussel** [comment]
Hey, just catching up here. 

I know the flattened representation of rows and interpretation of repetition and definition levels can be challenging to work with. Let me know if you have suggestions on what we could add to the library, it is always useful to hear from user experiences!

**Comment by Jeffail** [comment]
Okay so I think it's looking good. There's a fair amount of logic needed on my end to go to/from dremel rep and def levels so some nooks in there for bugs to hide but we now have two new processors (encode/decode) and a bloblang method (decode): https://github.com/benthosdev/benthos/commit/dd18100f85baae18d677cd168f0b1dca0c4276ab

Closing this issue for now as they'll be ready to try and use in the next release. Any subsequent bugs or features should be opened as separate issues.
