### ISSUE TITLE
/ready behavior doesn't exactly match up with documentation

### ISSUE THREAD

**Issue by sondermax** [benthosdev/benthos#1208]
hey there! first, love the project, really appreciate all the hard work that's gone into it :)

edit: 

```shell
~ % benthos --version
Version: 3.65.0
Date: 2022-03-08T05:14:05Z
```

according to [the docs](https://www.benthos.dev/docs/components/http/about/#endpoints):

`/ready can be used as a readiness probe as it serves a 200 only when both the input and output are connected, otherwise a 503 is returned.`

what's interesting is that if one cannot connect to kinesis, the `/ready` endpoint returns `200 OK` after the error is printed (note the timestamps):

```shell
# benthos process
~ % benthos  --log.level trace -s http.debug_endpoints=true -s output.aws_kinesis.stream='ooooooooooooooooooooooooo' -s output.aws_kinesis.partition_key='${!json("id")}' -s output.aws_kinesis.region='us-east-1'
{"@timestamp":"2022-04-11T14:32:40-04:00","@service":"benthos","component":"benthos","level":"INFO","message":"Launching a benthos instance, use CTRL+C to close."}
{"@timestamp":"2022-04-11T14:32:40-04:00","@service":"benthos","component":"benthos","level":"INFO","message":"Listening for HTTP requests at: http://0.0.0.0:4195"}
{"@timestamp":"2022-04-11T14:35:59-04:00","@service":"benthos","component":"benthos.output","level":"ERROR","message":"Failed to connect to aws_kinesis: ResourceNotReady: exceeded wait attempts"}
```

```shell
# console
~ % http GET localhost:4195/ready
HTTP/1.1 503 Service Unavailable
Content-Length: 21
Content-Type: text/plain; charset=utf-8
Date: Mon, 11 Apr 2022 18:32:45 GMT

output not connected


~ % http GET localhost:4195/ready
HTTP/1.1 200 OK
Content-Length: 2
Content-Type: text/plain; charset=utf-8
Date: Mon, 11 Apr 2022 18:36:19 GMT

OK

```

seems like this behavior isn't quite what the docs describe - it's problematic as readiness probes switch from `unready` to `ready`, despite the (only) output being errored out.

**Comment by Jeffail** [comment]
Thanks @sondermax, I think that's all the info we'll need, you're correct that you shouldn't be receiving a 200 response unless the output is available and connected. It's possible that the state of the output is such that it's aware that messages cannot flow but does not consider the issue a connectivity problem, in which case we might need to add some extra error handling to detect general connectivity problems with kinesis.
