### ISSUE TITLE
Add MongoDB aggregation filter supports

### ISSUE THREAD

**Issue by pcha** [benthosdev/benthos#1215]
Hi @Jeffail , I want to consume certain data from a mongo collection but using aggregation filters instead of a simple find.

I consider that this could be a great feature, and with only a little of effort to add. the existing `mongodb` input could support a field `operator` similar to the output, and if the value is "aggregate" instead of "find" (the default) the field `query` is taken as an aggregation pipeline.

As I see it the change consist in update the config structure, of course, and in the `Connect` method add something similar to:
```go
	switch m.config.Operation {
	case "find":
		m.cursor, err = collection.Find(ctx, m.query)
	case "aggregate":
		m.cursor, err = collection.Aggregate(ctx, m.query)
	default:
		return fmt.Errorf("Opertaion %s not supported. the supported values are \"find\" and \"aggregate\"", m.config.Operation)
	}
```
instead of only:
```go
m.cursor, err = collection.Find(ctx, m.query)
```

If you are ok I could work in this feature and send you the PR

**Comment by mihaitodor** [comment]
Hey @pcha, that sounds like a good enhancement. If you're happy to work on a PR, please do so and we'll help you with it.

**Comment by boorad** [comment]
PR is merged.  Is this issue safe to close?

**Comment by Jeffail** [comment]
Ooh yah, thanks for the poke @boorad.
