### ISSUE TITLE
Watch mode fails in streams mode

### ISSUE THREAD

**Issue by mariosant** [benthosdev/benthos#1221]
`watch` mode fails while trying to run in streams mode.

```
$ benthos -w -r "resources/*.yaml" streams streams/*.yaml
{"@timestamp":"2022-04-21T09:49:28+03:00","@service":"benthos","component":"benthos","level":"INFO","message":"Launching benthos in streams mode, use CTRL+C to close."}
{"@timestamp":"2022-04-21T09:49:28+03:00","@service":"benthos","component":"benthos","level":"ERROR","message":"Failed to create stream config watcher: no such file or directory"}
```

The above runs fine without the `-w` flag.
The above applies to benthos v3.65.0. I have not tried the super fresh v4.

**Comment by Jeffail** [comment]
Thanks @mariosant, confirmed that this is a bug with any wildcard resource or stream imports with the watcher flag. I've got a fix in v4: https://github.com/benthosdev/benthos/commit/5164c75961fa0a541a7ba15c8dd397e51316553e, is this something you need backporting for v3 as well?

**Comment by mariosant** [comment]
Thank you @Jeffail! I personally do not!
