### ISSUE TITLE
import plugin  separately

### ISSUE THREAD

**Issue by luxixing** [benthosdev/benthos#1230]
In v4, if I only want to use one of the plugins in interanl/impl, how do I import it?
I see there is https://github.com/benthosdev/benthos/tree/main/public/components/pulsar
So for example kafka, gcp, etc., if I use it, can I import it separately? Is it possible to import a plugin in 
https://github.com/benthosdev/benthos/tree/main/public/components to be exposed?

**Comment by Jeffail** [comment]
Hey @luxixing, it's a work in progress, once most of the last remaining items in https://github.com/benthosdev/benthos/tree/main/internal/old are migrated out we'll be able to offer more granular plugin imports. My guess would be in the next month or so we'll start getting minor version releases with more packages on offer, but it's reliant on how much time I get to spend on it.
