### ISSUE TITLE
Add support for headers in the `nats_jetstream` component

### ISSUE THREAD

**Issue by albinou** [benthosdev/benthos#1238]
The `nats` output has a `headers` field that allows to set message headers (see [documentation](https://www.benthos.dev/docs/components/outputs/nats#headers)).

I would need the same support for the `nats_jetstream` output. This would actually consists in:

1. reading headers in the input
2. being able to write a set of headers in output

I already began the implementation and I will probably propose this enhancement soon. Meanwhile, don't hesitate to comment.

**Comment by mihaitodor** [comment]
Hey @albinou, thanks for raising this! It sounds like a good addition, so please feel free to send a PR.
