### ISSUE TITLE
Feature Request: Add TLSTrustCertsFilePath option to Pulsar input and output

### ISSUE THREAD

**Issue by bemoore34** [benthosdev/benthos#1245]
**Request**: Add the Pulsar Client option to provide a CA certificate for trusting internally signed certificates.

I apologise if there is another way to support this in Benthos, but I couldn't find one.

When using TLS encrypted Broker connections ("pulsar+ssl://<URL/IP>:6651") the Pulsar client requires the signing CA's Cert in order to trust self-signed certificates. Without this, the client returns: `error="x509: certificate signed by unknown authority"`

Support for providing a CA cert can be added with the `TLSTrustCertsFilePath` option. This could be added to the pulsar.ClientOptions in the Pulsar input/output Connect methods along with the appropriate updates to the pulsarReader/Writer struct and config parsing:
```
opts := pulsar.ClientOptions{
		Logger:                 createDefaultLogger(p.log),
		ConnectionTimeout:      time.Second * 3,
		URL:               	p.url,
		TLSTrustCertsFilePath:  p.caCert
	}
```
Reference: https://pulsar.apache.org/docs/en/client-libraries-go/#tls-encryption-and-authentication

**Comment by mihaitodor** [comment]
Hey @bemoore34, indeed, we are not setting that option in the input and output [here](https://github.com/benthosdev/benthos/tree/main/internal/impl/pulsar). Should be a straightforward addition. I think Ash will be happy to accept a PR if you'd like to contribute.

**Comment by bemoore34** [comment]
@mihaitodor, that sounds good, I would be happy to contribute. I'll try to do that in the next couple days.
