### ISSUE TITLE
Support `JSON` and `JSONB` data types in PostgreSQL output

### ISSUE THREAD

**Issue by pablojimpas** [benthosdev/benthos#1252]
Hello everyone, thank you for making benthos what it is today, such a useful tool.

I'm using the `sql_insert` output and I want to achieve mapping some JSON directly to a column in a PostgreSQL database that has the `JSONB` data type.

Right now and I get the following error message:
```
Failed to dispatch switch message: sql: converting argument $19 type: unsupported type []interface {}, a slice of interface
```

I don't know if this is an issue with benthos itself, the underlying `postgres` driver not being able to handle this date types or that I'm doing something silly, but at least it seems to me that this it's not a desirable behavior.

**Comment by Jeffail** [comment]
Hey @pablojimpas, might need testing as I'm not 100% sure but you likely need to stringify the value you're inserting into the column, then since it'll be serialized as valid JSON the conversion should work, something like this:

```yaml
args_mapping: 'root = [ this.foo.string() ]'
```

**Comment by Jeffail** [comment]
Hey @pablojimpas, might need testing as I'm not 100% sure but you likely need to stringify the value you're inserting into the column, then since it'll be serialized as valid JSON the conversion should work, something like this:

```yaml
args_mapping: 'root = [ this.foo.string() ]'
```

**Comment by pablojimpas** [comment]
Ahhh thanks @Jeffail I totally missed that `.string()` method! Closing this issue since it's already supported and works great with this simple tweak.
