### ISSUE TITLE
Watcher in streams mode: watch for new file or deleted file

### ISSUE THREAD

**Issue by norbjd** [benthosdev/benthos#1257]
Hello! :wave:

## Issue

I can't make Benthos work in Streams mode with watcher option when **adding new files or removing files**:

- adding new files does not trigger a loading of the new config
- removing an existing file won't remove the stream

I don't know if this is by design or not.

## How to reproduce?

I am using Docker to run Benthos, with the latest Benthos version at the moment (4.1.0):

```shell
docker run --name benthos --rm -it -p 4195:4195 \
    -v $PWD/configs:/configs \
    jeffail/benthos:4.1.0 --watcher streams /configs/*.yaml
```

Benthos is running, I can see the following logs:

```
Config file not specified, reading from /benthos.yaml
INFO[0000] Launching benthos in streams mode, use CTRL+C to close.  @service=benthos
INFO[0000] Listening for HTTP requests at: http://0.0.0.0:4195/  @service=benthos
```

When starting the container, my `/configs` directory **is empty**, so `curl http://localhost:4195/streams` returns `{}`, as expected.

But if I create a file in the `/configs` directory, either by copying a `yaml` or directly by `touch`ing a file and then editing it, logs does not show that Benthos have loaded my new config file. I can confirm that no streams are added because `curl http://localhost:4195/streams` still returns `{}`. I have also waited 5 minutes (in case there was some delay), but without success.

For info, my config (simple NATS -> HTTP) is valid, because if I restart my container after adding the new file in my `configs` directory, the logs show:

```
INFO[0000] Sending messages via HTTP requests to: https://domain.com/  @service=benthos label="" path=root.output stream=hello
INFO[0000] Receiving NATS messages from JetStream subject: sub1  @service=benthos label="" path=root.input stream=hello
```

I know that if I start my container with one config (like `hello.yaml`) and if I change **this particular** config, it will be reloaded, as the docs states.

## Question

So I have experienced the two following behaviors:

- when adding a new file, the new config is not loaded
- when removing an existing file, the associated stream won't disappear (`curl http://localhost:4195/streams` will still return the stream corresponding to the deleted file)

Are these behaviors normal? If so, can those features (loading new files and deleting streams if files are deleted) be added? It will be really great for dynamic configuration with files of Benthos!

I'm also thinking: maybe if **all streams were defined in a single file**, the reload will work since the file name won't change, and reloading works great. But I'm wondering if having multiple streams in one file is possible. It could be one way to mitigate my issue temporarily.

Thanks for reading and thanks in advance for your help!

**Comment by Jeffail** [comment]
Hey @norbjd, the watcher behaviour is intentionally quite limited right now. The plan is to support delete and creation events on wildcard paths but I didn't want to rush the feature through as we need to consider interactions with resources.

The current behaviour is to resolve wildcard paths immediately and then follow the files that match at start up. I'm going to tag this issue as an enhancement as this'll be done eventually.

**Comment by Jeffail** [comment]
Closing for now but if anything comes up I'd like to reopen and reuse this issue.
