### ISSUE TITLE
Benthos 4 - hostname() function  ot working inside metrics mapping

### ISSUE THREAD

**Issue by AlmogAlmado** [benthosdev/benthos#1270]
Setup:
     metrics:
        mapping: |
            root = "benthos_"+this.replace("-", "_").replace(".", "_")
            meta pod_name = hostname()
        prometheus:
            add_process_metrics: true
            add_go_metrics: false

Error:
{"@service":"benthos","level":"error","msg":"Failed to connect to metrics aggregator: line 2 char 17: unrecognised function 'hostname'","time":"2022-05-23T16:33:36Z"}

P.S
with now() function no issue

**Comment by Jeffail** [comment]
Hey @AlmogAlmado, looks like the mapping is restricted to only "pure" methods and functions. I'm not entirely sure why that was changed, I'll mark this as high priority and have it added back in the next release.

**Comment by AlmogAlmado** [comment]
thanks @Jeffail , you rock :)

I'm using this as a workaround for now, till the next release is ready
*pod creation 
export server=$(hostname)

*config yaml
     metrics:
        mapping: |
            root = "benthos_"+this.replace("-", "_").replace(".", "_")
            meta pod_name = "${server}"

**Comment by Jeffail** [comment]
Fixed: https://github.com/benthosdev/benthos/commit/4d60f262ef7e61d51ceb36d3891887e74eab9bfc
