### ISSUE TITLE
Streams Mode Crash

### ISSUE THREAD

**Issue by nmstone** [benthosdev/benthos#1278]
Hello!

Have been really enjoying using benthos but have run into an issue that i'm having trouble wrapping my head around. For context, I am using streams mode to create short lived streams that use the file input and a variety of outputs. Essentially when a dynamically named file becomes ready, I create a stream with a file input and an HTTP output with concurrency 10, poll for completion of the stream, then delete the stream. This works well, but am seeing benthos crash after around 4-5 hours (creating, completing, and deleting about 3 pipelines every ten minutes ~80 total streams before crashing).

I have an error message below, but it seems as if the machine I am running on gets out of memory errors at the same time that benthos crashes. It's possible that my machine is incorrectly sized, but the data sets are not particularly large and the machine is decently large. I need to continue investigating, but I am wondering if there is a possible memory leak when creating and deleting many streams, as my usage of creating and deleting many streams does not seem to be the normal usage pattern.

I am on version 4.1.0. As a side note, when I was running on v3 I would crash after around 30 minutes.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfb24c0]

goroutine 3410 [running]:
github.com/benthosdev/benthos/v4/internal/stream/manager.(*StreamStatus).setClosed(...)
	/home/ubuntu/testing/benthos/internal/stream/manager/type.go:77
	github.com/benthosdev/benthos/v4/internal/stream/manager.(*Type).Create.func1()
		/home/ubuntu/testing/benthos/internal/stream/manager/type.go:153 +0x20
		github.com/benthosdev/benthos/v4/internal/stream.(*Type).start.func1({0x36ae240, 0xc001ec3260})
			/home/ubuntu/testing/benthos/internal/stream/type.go:135 +0x5a
			created by github.com/benthosdev/benthos/v4/internal/stream.(*Type).start
				home/ubuntu/testing/benthos/internal/stream/type.go:132 +0x590\n
```

Let me know if there is additional information I can provide. And thank you for such a great project!

**Comment by Jeffail** [comment]
I believe this is fixed https://github.com/benthosdev/benthos/commit/70b839268d3cb851038630592c88f2595af91c68, it was a race condition caused when creating new streams that shut themselves down, specifically when it happens quickly. This could have been a file that was either very small or empty.

I'm planning a release this week but if you want to try it sooner there'll be a nightly release, so tomorrow you should be able to pull the docker image `jeffail/benthos:edge` and run it that way.

**Comment by Jeffail** [comment]
Released: https://github.com/benthosdev/benthos/releases/tag/v4.2.0, closing but please reopen if you can still reproduce this.
