### ISSUE TITLE
Unable to infer prometheus

### ISSUE THREAD

**Issue by boytunp** [benthosdev/benthos#1290]
Hi. I am trying to  upgrade to 4.2 the linter doesn't like:
![image](https://user-images.githubusercontent.com/23097617/173312299-c0fb451e-0f4a-4d37-8f05-2d746977dc72.png)
I also tried it in the visual tool still don't like it. 
![image](https://user-images.githubusercontent.com/23097617/173312594-2ec5d861-b18b-4137-a378-c893dbaa46f4.png)

Went throught the docs and looks like this still should work in 4.2. Might be a bug here.

**Comment by Jeffail** [comment]
Hey @boytunp is this with an official distribution of benthos or a custom build you're running? I'm seeing the issue on benthos studio and I'll need to fix that separately.

**Comment by boytunp** [comment]
All official here

**Comment by Jeffail** [comment]
Docs updated: https://github.com/benthosdev/benthos/commit/9ee3ba3a8d3993821acad8b4852ba44ab005d5d2, I'll follow up with a studio fix separately.
