### ISSUE TITLE
amqp_0_9 deadlock waiting  ack 

### ISSUE THREAD

**Issue by sapk** [benthosdev/benthos#1299]
During load testing, I found that benthos can stay deadlock on amqp_0_9 output waiting for ack here: https://github.com/benthosdev/benthos/blob/main/internal/impl/amqp09/output.go#L282

This can lead to full deadlock of the benthos processing since the message is not released and no error is triggerred.

It happen randomly near millions of messages processing and maybe related to a bug on amqp side but it maybe possible to add a (configurable) timeout on benthos side. 
This could in this case trigger a timeout error and allow any error handling in benthos like the resubmitting of the message. 

Stack trace of the locked goroutine:
```
goroutine 261 [semacquire, 19 minutes]:
sync.runtime_Semacquire(0x101d7c0?)
	/usr/local/go/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0xc00126fb90?)
	/usr/local/go/src/sync/waitgroup.go:136 +0x52
github.com/rabbitmq/amqp091-go.(*DeferredConfirmation).Wait(...)
	/go/pkg/mod/github.com/rabbitmq/amqp091-go@v1.3.4/confirms.go:178
github.com/benthosdev/benthos/v4/internal/impl/amqp09.(*amqp09Writer).WriteWithContext.func1(0xc004b6ea70?, 0x0?)
	/go/src/github.com/benthosdev/benthos/internal/impl/amqp09/output.go:282 +0x487
github.com/benthosdev/benthos/v4/internal/component/output.IterateBatchedSend(0x440c20?, 0xc00126fb60?)
	/go/src/github.com/benthosdev/benthos/internal/component/output/batched_send.go:34 +0x10d
github.com/benthosdev/benthos/v4/internal/impl/amqp09.(*amqp09Writer).WriteWithContext(0xc00067d180, {0x36c9ce0?, 0xc0000d4000?}, 0xc003a72eb8)
	/go/src/github.com/benthosdev/benthos/internal/impl/amqp09/output.go:237 +0x10b
github.com/benthosdev/benthos/v4/internal/component/output.(*AsyncWriter).latencyMeasuringWrite(0xc001905e30, 0xf?)
	/go/src/github.com/benthosdev/benthos/internal/component/output/async_writer.go:104 +0xbe
github.com/benthosdev/benthos/v4/internal/component/output.(*AsyncWriter).loop.func4()
	/go/src/github.com/benthosdev/benthos/internal/component/output/async_writer.go:254 +0x35d
created by github.com/benthosdev/benthos/v4/internal/component/output.(*AsyncWriter).loop
	/go/src/github.com/benthosdev/benthos/internal/component/output/async_writer.go:292 +0x5dc
```
[benthos-stack.txt](https://github.com/benthosdev/benthos/files/8928598/benthos-stack.txt)

**Comment by Jeffail** [comment]
Hey @sapk thanks for raising this and for the stack trace. Unfortunately we're quite limited on our end as the method doesn't support any form of cancellation: https://pkg.go.dev/github.com/rabbitmq/amqp091-go#DeferredConfirmation so we rely entirely on the client internals working in our favour.

The client library is quite active and seems to be well maintained so I'll make a note to upgrade and if you're still seeing issues with the latest version we can look into raising it with them.

**Comment by sapk** [comment]
I will open an issue on rabbitmq repository linking to these one to discuss the solution with the lib.
