### ISSUE TITLE
bloblang: backslashes are doubled

### ISSUE THREAD

**Issue by billgraziano** [benthosdev/benthos#1301]
I've been struggling to handle backslashes.  I live mostly in the Windows world.  I often get usernames and SQL Server instances that have backslashes in the names such as or DOMAIN\computer or COMPUTER\INSTANCE.  Code is at the bottom.  It seems to double each backslash.  Here is the result:

```
input: map[s1:test\test s2:test\\test]
-----------------------------
{
  "s1": "test\\test",
  "s1_upper": "TEST\\TEST",
  "s2": "test\\\\test"
}
```
And the code that generated it:
```go
package main

import (
	"encoding/json"
	"fmt"
	"log"

	"github.com/benthosdev/benthos/v4/public/bloblang"
	_ "github.com/benthosdev/benthos/v4/public/components/io"
)

func main() {
	mapping := `
		root = this
		root.s1_upper = this.s1.uppercase()
	`
	exe, err := bloblang.Parse(mapping)
	if err != nil {
		log.Fatal(err)
	}
	object := map[string]interface{}{}
	object["s1"] = `test\test`
	object["s2"] = `test\\test`
	fmt.Printf("input: %v\n", object)

	res, err := exe.Query(object)
	if err != nil {
		log.Fatal(err)
	}

	jsonBytes, err := json.MarshalIndent(res, "", "  ")
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("-----------------------------")
	fmt.Println(string(jsonBytes))
}

```

**Comment by Jeffail** [comment]
Hey @billgraziano, that's just how JSON strings work. A backslash is used to escape certain characters (double-quotes for example), so a backslash literal itself needs to be escaped.

Literal string: `foo " bar`, JSON string: `"foo \" bar"`
Literal string:
```
foo
bar
```
JSON string: `"foo\nbar"`
Literal string: `foo\bar`, JSON string: `"foo\\bar"`

**Comment by billgraziano** [comment]
HA!  So it is.  :-)
