### ISSUE TITLE
bloblang online playground

### ISSUE THREAD

**Issue by oliverpool** [benthosdev/benthos#1320]
Hi, there is already a playground available via `benthos blobl server`.

However it is possible to provide an online playground using wasm.
I have a working prototype (15MB of wasm is quite heavy, but still lighter as any docker image ;-)

![2022-07-09-144655](https://user-images.githubusercontent.com/3864879/178106404-7489cce9-9b57-4592-a5d8-801a9ba21feb.png)

If you find this interesting and want to propose it to your users, let me know where you would see it online (dedicated subdomain, some page one benthos.dev, github.io hosting...)

**Comment by Jeffail** [comment]
Very neat, I made https://lab.benthos.dev a while ago as an experiment but there's now https://studio.benthos.dev/ which does server-side validation and testing.

**Comment by oliverpool** [comment]
> https://lab.benthos.dev/

Very nice, so my experiment is 3 year to late :laughing: 

> https://studio.benthos.dev/

I saw this, but stopped when it asked me to log-in :see_no_evil: 
(the source of the "studio" is not public, I guess)
