### ISSUE TITLE
logger: option to rename time field?

### ISSUE THREAD

**Issue by sondermax** [benthosdev/benthos#1324]
hi there! thanks for your continued awesomeness in this project :) 

the v4 migration renamed the `@timestamp` field to just be `time`, if enabled. was curious if there would be any utility in allowing configuration of this field's name?

- some tools really want a particularly formatted timestamp field (for example, datadog UI, or old code that used `@timestamp` 😛 )
- the logger can't use functions in `static_fields`, so there can't be a custom field added there to get around it

any thoughts here? of course, if i'm missing something super obvious, forgive me and i'll check it out!

thanks again!!

edit: be clearer about configuration the name of the field

**Comment by Jeffail** [comment]
Hey @sondermax, that'll be from migrating the underlying logger to logrus. I think it's reasonable to customise the field name, especially since we changed it from v3. Maybe a new field `timestamp_name: time`, will try and get this in the next release.

**Comment by Jeffail** [comment]
Labelling a bughancement since it was a stink to silently change the field name in v4.

**Comment by Jeffail** [comment]
Done: https://github.com/benthosdev/benthos/commit/d5da5fd40fce575c4bd6ed9b6a2511a729acb76c

**Comment by sondermax** [comment]
you are the best! ❤️‍🔥
