### ISSUE TITLE
Mongo processor write_concern defaults invalid

### ISSUE THREAD

**Issue by DeusFacticius** [benthosdev/benthos#1331]
Benthos build info:
```shell
# benthos --version
Version: 4.4.1
Date: 2022-07-19T07:37:50Z
```
Also tested against the version in the `jeffail/benthos:4.3` docker image.

When using the `mongodb` processor with a mongodb replica set; if the `write_concern.w_timeout` field is omitted (and so should implicitly adopt the default of `""` (an empty string), according to current documentation); benthos will fail to initialize with a somewhat cryptic error:
```
level=error msg="Service closing due to: failed to init processor (...path to mongodb processor block...): failed to parse wtimeout string: time: invalid duration \"\"" @service=benthos
```

After a bit of googling, it seems like this stems from unmarshalling a Go time duration value from a string during YAML processing.

A few insights:
* This does not happen until _after_ benthos has established a connection to the replica set (e.g. the parsing itself seems to be lazy, not fully parsed until after the URL is resolved, benthos has connected, discovered the replicaset members, and established a connection with all of them)
* This happens even if the `operation` field is `'find-one'` (and so write_concern is moot)
* `lint` does not catch this error.

The workaround is to explicitly specify a valid `write_concern.w_timeout` value, so it's not terribly difficult to overcome, but this definitely ate through a few hours this morning, hopefully this ticket will save someone else from chasing the same ~~squirrel~~  blobfish.

**Comment by Jeffail** [comment]
Hey @DeusFacticius thanks for raising this and sorry to hear about your struggles, I've changed our config parser to allow for empty values: https://github.com/benthosdev/benthos/commit/0a0b3c85a6d58cf1c8f68aeddaaefd0160704f69
