### ISSUE TITLE
Parse form urlencoded http requests

### ISSUE THREAD

**Issue by mariosant** [benthosdev/benthos#1348]
It would be great if benthos could parse form urlencoded data when sent to an http server input.

Example payload:
```
username=mariosant&email=lorem%40example.com
```

More to that:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST#example

**Comment by mihaitodor** [comment]
The [`parse_form_url_encoded` bloblang method](https://www.benthos.dev/docs/guides/bloblang/methods#parse_form_url_encoded) was added in [v4.5.1](https://github.com/benthosdev/benthos/releases/tag/v4.5.1).
