### ISSUE TITLE
Feature suggestion: Add snowflake ID to boblang

### ISSUE THREAD

**Issue by ehcaning** [benthosdev/benthos#1377]
Hey, Benthos Team.

Recently we come is a situation that we could use `Snowflake ID` in Benthos. 
If it sounds like a good idea, I'd be more than happy to create a PR and add this feature.

**Comment by mihaitodor** [comment]
Sure, that sounds like a reasonable thing to add. Please go ahead and send a PR

**Comment by ehcaning** [comment]
@mihaitodor Hey, there is a PR ready to review to address this.
https://github.com/benthosdev/benthos/pull/1379
Thanks for your time.
