### ISSUE TITLE
Update Clickhouse driver, so it will support insert of experimental semi-structured JSON feature + insert DateTime from string

### ISSUE THREAD

**Issue by isae** [benthosdev/benthos#1396]
For now, to implement such pipeline, I had to add temporary table with raw JSON and insert from Benthos to it + add materialized view with transformation.

**Comment by mihaitodor** [comment]
Any idea if #1397 will suffice?

**Comment by isae** [comment]
@mihaitodor yes, I just checked, it works. Thank you, hope it will be merged soon.
