### ISSUE TITLE
Error when querying dynamic input HTTP API (/inputs give 502 Bad Gateway)

### ISSUE THREAD

**Issue by norbjd** [benthosdev/benthos#1422]
Hello :wave: 

We are facing an issue to query the HTTP API to retrieve the input status when using `dynamic`. We are using Benthos version 4.5.1, and here's a simple config to reproduce:

```yaml
input:
  dynamic:
    inputs:
      input1:
        stdin: {}

output:
  stdout: {}
```

We are starting benthos with `benthos -c config.yaml`, it works correctly (sending a message to stdin prints the message on stdout).

But when querying the HTTP API, we have an unexpected error (502) when querying `/inputs`:

```shell
$ curl http://localhost:4195/inputs/input1 # works, but we could not see the status of the input
label: ""
stdin:
    codec: lines
    max_buffer: 1000000

$ curl http://localhost:4195/inputs # 502 Bad Gateway, no trace in the server
Internal server error

$ curl http://localhost:4195/inputs/ # normal, I think
404 page not found
```

We can't see any error on the Benthos instance when querying `/inputs`, so unfortunately we can't debug further :(

Our use-case is to list the inputs and check which of them is stopped or not working due to a misconfiguration.

Do you have any idea ? Thanks !

**Comment by Jeffail** [comment]
Hey @norbjd, yeah this is a bug introduced in V4, there's a fix ready for the next release, more info here: https://github.com/benthosdev/benthos/issues/1398

**Comment by norbjd** [comment]
Oops, sorry about the duplicate, I was looking for open issues on that topic and did not found it since it was closed! Thank you :)
