### ISSUE TITLE
System window by key

### ISSUE THREAD

**Issue by webfrank** [benthosdev/benthos#1447]
Hi, I've setup a pipeline to process messages coming from sensors over MQTT. 

Messages are sent every second and I would like to have the max value over 1 minute by serial. 

I've setup a buffer system window with size 1minute and a pipeline with a group by value to batch together readings from same serial. After that I can calculate max or any other value. 

The issue is with the system window which is unique for all the messages. I would like to have multiple windows, one per serial/key. 

Is it possible to achieve this with benthos? It would be like partitioning data by key. 

Thank you.

**Comment by Jeffail** [comment]
Hey @webfrank, not sure I fully understand your goals, any chance you can outline a typical input versus desired outputs? The system window implementation is super barebones right now and I'd love to expand it so I'm hungry for use cases. I also want to have an event time windower as an alternative but I'm not sure that would help in your case.
