### ISSUE TITLE
Add configurable backoff to aws_sqs input

### ISSUE THREAD

**Issue by siviae** [benthosdev/benthos#1449]
The problem: right now aws_sqs input generates one error log per second if queue does not exists or the application has insufficient permissions to receive messages from it. This generates huge amount of logs very fast, especially if there are multiple sqs queues which could be added and removed dynamically (my case). It would be nice if it had backoff configuration, so I could add exponential backoff behaviour and drastically shorten the amount of logs.

**Comment by Jeffail** [comment]
Hey @siviae yeah that sounds really annoying, we should do backoff generally but maybe be more aggressive with it for longer term errors like permissions etc.

**Comment by Jeffail** [comment]
@siviae I think to start I'd be happy just adding a backoff policy without any configuration, as long as it's sensible I doubt anyone would be interested in tuning it. If there's demand for customisation later we can consider which parameters to expose at that point.
