### ISSUE TITLE
Incorrect data processing when reading from MongoDB 

### ISSUE THREAD

**Issue by its-a-setup** [benthosdev/benthos#1452]
**Message in MongoDB:**
{

    "check" : "1",
    "test1":[
       {
          "test2":{
             "test3":"Target"
          }
       }
    ]
}

**Code, which suppose to work, but doesn't:**
input:
  label: raw_input
  mongodb:
    url: mongodb+srv://atlascluster
    database: mock_data
    collection: test_col
    username: 
    password: 
    operation: find
    query: 'root.check = {"$eq": "1"}'
pipeline:
  processors:
    - bloblang: |-
        root = this.test1.0.test2.test3
output: {}

**Expected output:** Target

**Code, which works:** 
input:
  label: raw_input
  mongodb:
    url: mongodb+srv://atlascluster
    database: mock_data
    collection: test_col
    username: 
    password: 
    operation: find
    query: 'root.check = {"$eq": "1"}'
pipeline:
  processors:
    - bloblang: 'root = content().parse_json()'
    - bloblang: |-
        root = this.test1.0.test2.test3

**Comment by Jeffail** [comment]
Forgot to update the ticket but i think this may be fixed with https://github.com/benthosdev/benthos/commit/bba343528c791cd22c7cd811923a94a6437dfa2f

**Comment by Jeffail** [comment]
Closing for now, if this hasn't resolved the problem feel free to reopen.
