### ISSUE TITLE
Allow controlling of the prefetch count on redis_list input

### ISSUE THREAD

**Issue by sarnikowski** [benthosdev/benthos#1469]
As discussed in https://github.com/benthosdev/benthos/discussions/1451, it seems that the greedy behavior of the `redis_list` input prefetching, cannot be controlled in a meaningful way. I would argue that it could be useful to be able to control this given the following reasons (note, motivated by personal needs, not necessarily representative):

1. If you have a distributed setup (for example in k8s), where you have multiple Benthos instances essentially acting as a workers, it would make sense that this count can be adjusted, to avoid worker starvation. This is particularly true if the mean task execution time is more than just a couple of seconds (which is my case), while at times having a slow stream of new items being put on the redis list.
    
    I don't really have a use-case for optimizing fetching items from the redis list, as the actual pipeline work is of magnitudes higher in execution time. So in this case I am fine with fetching a single item a time, with the potential risk of loosing some I/O throughput speed (as I imagine this greedyness perhaps helps with).
3. For the purpose of observability, specifically, I would like to know which items are currently being worked on (not just having been fetched and awaiting to be put through the pipeline) versus queued. I guess I could achieve it by having some initial step in the processor, which should expose this information, but it seems quite cumbersome to be able to do a simple distinction between queued/processing. Because not only do I have to count the items on the redis_list I also have to count those that have been popped, but are awaiting processing inside Benthos.

Perhaps I am misusing Benthos, and there are better ways to achieve this ! Should the change to control this however be reasonably easy to implement, I do not necessarily an issue in exposing it for configuration. But I leave the judgement of that up to you :). Thanks !

**Comment by mihaitodor** [comment]
For 2, I wonder if the [default processor metrics](https://www.benthos.dev/docs/components/metrics/about#processors) might help. More specifically, `processor_received`, `processor_batch_received`, `processor_sent` and `processor_batch_sent`. If not, the [`metric` processor](https://www.benthos.dev/docs/components/processors/metric) can be used to emit a custom metric as I think you're suggesting.

**Comment by Jeffail** [comment]
Hey, been thinking about this and it's actually fairly straight forward to implement an explicit prefetch count. When a message is consumed it's associated with a closure used for acknowledging, it's unused right now as redis lists dont have any form of nack so the component is wrapped in an auto-retry for nacks instead, but the closure is still there as a signal on acks: https://github.com/benthosdev/benthos/blob/main/internal/impl/redis/input_list.go#L121, we could block the read call on a semaphore of a fixed size (the prefetch count) and release it within that ack function and that way we'd limit the the number of messages fetched.

We already do something similar to this with the kafka input with the `checkpoint_limit` field as a way of limiting the number of partition messages to process outside of commits.

Only question is what to call it, it's not an explicit prefetch as we're limiting both the number of popped list items but also the number of items that can be processed. We could reuse `checkpoint_limit` to maybe standardise on that but it's kind of cryptic, you'd need to read the field docs to know what it does, but maybe that's a good thing as well.

It's worth noting that there would be caveats to this approach, if you have a batch policy at the output level then the message won't be acked until the batch is flushed, if you don't allow the input to consume enough messages to trigger the batch then it stalls.

**Comment by sarnikowski** [comment]
> we could block the read call on a semaphore of a fixed size (the prefetch count) and release it within that ack function and that way we'd limit the the number of messages fetched.

Yes, this sounds good !

> It's worth noting that there would be caveats to this approach, if you have a batch policy at the output level then the message won't be acked until the batch is flushed, if you don't allow the input to consume enough messages to trigger the batch then it stalls.

Yes, and for the use-case that I have described I think this is just fine, but I agree that it would be great to add to the documentation (as I think you are already implying).

**Comment by sarnikowski** [comment]
I would be happy to take a stab at this.
