### ISSUE TITLE
How to process JSONP

### ISSUE THREAD

**Issue by packman80** [benthosdev/benthos#1474]
In my case i need process jsonp (json with callback). I did http request via benthos and got this body

`/**/_xdc_._8dl8id && _xdc_._8dl8id( {
   "results" : [
      {
         "address_components" : [
            {
               "long_name" : "1",
               "short_name" : "2",
               "types" : [ "locality", "political" ]
            },
            {
               "long_name" : "1",
               "short_name" : "2",
               "types" : [ "administrative_area_level_3", "political" ]
            },
            {
               "long_name" : "1",
               "short_name" : "RP",
               "types" : [ "administrative_area_level_1", "political" ]
            },
            {
               "long_name" : "2",
               "short_name" : "DE",
               "types" : [ "country", "political" ]
            }
         ],
         "formatted_address" : "1, 2",
         "geometry" : {
            "bounds" : {
               "northeast" : {
                  "lat" : 49.9158037,
                  "lng" : 7.056334799999999
               },
               "southwest" : {
                  "lat" : 49.8852594,
                  "lng" : 6.9985839
               }
            },
            "location" : {
               "lat" : 49.9070233,
               "lng" : 7.014203699999999
            },
            "location_type" : "APPROXIMATE",
            "viewport" : {
               "northeast" : {
                  "lat" : 49.9158037,
                  "lng" : 7.056334799999999
               },
               "southwest" : {
                  "lat" : 49.8852594,
                  "lng" : 6.9985839
               }
            }
         },
         "place_id" : "ChIJXxx5ZkYvvkcRgPLaENXUIgQ",
         "types" : [ "locality", "political" ]
      }
   ],
   "status" : "OK"
}
 )`

I need delete this parts ('/**/_xdc_._8dl8id && _xdc_._8dl8id( ' and ')' and make a valid json. Is it possible to do that via bloblang ?

**Comment by Jeffail** [comment]
Hey @packman80, that's a nasty one but it looks as though you can get away with this: `root = content().slice(content().index_of("{")).trim(")").parse_json()`. Basically we look for the first squiggly bracket of the JSON and then trim the `)` suffix. I'm not that familiar with jsonp so not sure how flexible this is, there could well be some edge cases it fails with.

**Comment by packman80** [comment]
Works like a charm! Thanks!
