### ISSUE TITLE
Proposed `ts_add_iso8601` method for large periods and leap dates

### ISSUE THREAD

**Issue by egbuk** [benthosdev/benthos#1499]
Current `parse_durration` and `parse_duration_iso8601` functions allow only rough approximation result for periods specified in units larger than hours according to [underlying library documentation of Period.DurationApprox](https://pkg.go.dev/github.com/rickb777/date@v1.20.0/period#Period.DurationApprox), so there is no reliable way to get date of next monthly command launch given current date and period.

I applied Benthos for monitoring of cron commands. Оn command completion pipeline receives it's tags and launch frequency specified in iso8601, so for command described in cron as "at 03:00 on 1st day-of-month" or `0 3 1 * *`, which represents actual system time parameters required for launch, `parse_duration_iso8601` receives period `P1M` and current date. For date October 1, 2022 3:00:00 AM addition of parsed duration with `parse_duration_iso8601("P1M")+this.last` will be computed as (365.2425/12)\*24\*60\*60+1664593200=1667222946 which is not quite there with October 31, 2022 1:29:06 PM, while [Period.AddTo from the same library](https://pkg.go.dev/github.com/rickb777/date@v1.17.0/period#Period.AddTo) allows much greater precision resulting to solid 1667271600 provided the same input, backed by built-in time library in go dealing with messy leaping dates logic.

Proposed method `ts_add_iso8601` should be called on timestamp value, parse parameter string as ISO 8601 period and add it to value with high percision for units larger than hour. It also would be good to implement `ts_sub_iso8601` utilizing [Period.Negate](https://pkg.go.dev/github.com/rickb777/date@v1.17.0/period#Period.Negate), just in case. Example usage:
```JS
root.next = this.last.ts_add_iso8601("P1M")
root.prev = this.last.ts_sub_iso8601("P1M")

# In:  {"last":"2022-10-01T03:00:00Z"}
# Out: {"next":"2022-11-01T03:00:00Z", "prev":"2022-09-01T03:00:00Z"}
```

**Comment by Jeffail** [comment]
Merged: https://github.com/benthosdev/benthos/commit/fbfe939768733695ab258f43c45666953c364a8a, thanks @egbuk!
