### ISSUE TITLE
How to set encoding in parquet data

### ISSUE THREAD

**Issue by skyoct** [benthosdev/benthos#1504]
Hello,
An error is reported when I use Spark3.2 to read the parquet generated file
```
Caused by: java.lang.UnsupportedOperationException: Unsupported encoding: DELTA_LENGTH_BYTE_ARRAY
	at org.apache.spark.sql.execution.datasources.parquet.VectorizedColumnReader.getValuesReader(VectorizedColumnReader.java:345)
```
according to the [issue](https://github.com/segmentio/parquet-go/issues/261),  i need to set the encoding. How can I set the encoding in benthos？

**Comment by Jeffail** [comment]
Hey @skyoct unfortunately we don't expose enough options for that right now, we'll need to add a new field.

**Comment by skyoct** [comment]
@Jeffail Thank you very much！
When can add this field?

**Comment by Jeffail** [comment]
Hey @skyoct, I've added a `default_encoding` field that you can set to `PLAIN` now which should solve this: https://github.com/benthosdev/benthos/commit/547723e3ab6b49881d7f52a1e350d418080a261e

**Comment by skyoct** [comment]
@Jeffail Thank you very much for your help！
