### ISSUE TITLE
Add `with` method to Bloblang

### ISSUE THREAD

**Issue by kisialiou** [benthosdev/benthos#1528]
Bloblang has very convinient [`without`](https://www.benthos.dev/docs/guides/bloblang/methods/#without) method which allows to exclude some fields from the message. 

However, as it was mentioned in Benthos Discord, often there're cases when one would rather include **only certain fields** from the message (e.g. there's a need in 2 fields out of 100). In this situation it'd be very convinient to have a `with` method which would select only these specific fields.

Example of usage:

```
# input: {"name": "alice", "friend": "bob", ..., "foo": "bar"}

root = this.with("name", "friend")

# output: {"name": "alice", "friend": "bob"}

```

**Comment by Jeffail** [comment]
hey @kisialiou, it's already implemented ready for the next release :smiley: I forgot to update you on the discord

**Comment by kisialiou** [comment]
Great, thank you!
