### ISSUE TITLE
is there any file watcher/polling component available?

### ISSUE THREAD

**Issue by dhaldergit** [benthosdev/benthos#1544]
Hi, 

is there any watcher/polling component available for files/folders so that moment new files(csv) are placed my task can start processing?
I have already explored sftp component has similar feature. but sftp is not relevant in my scenario.

**Comment by mihaitodor** [comment]
Hey @dhaldergit, I think issue #271 covers this. Feel free to chime in there and describe your use case and let me know if you're OK to close this one as a dupe.
