### ISSUE TITLE
Snowflake_put output: Auth token expires after 4 hours of inactivity

### ISSUE THREAD

**Issue by niclasgrahm** [benthosdev/benthos#1556]
My setup (kafka input, snowflake_put output) gets its data sporadically, usually in a burst once per day.

I get the following error:
<img width="942" alt="snowflake_auth_error" src="https://user-images.githubusercontent.com/97113706/199694769-bac0b568-903a-413d-b7e3-56a1764ab658.png">

Apparently a snowflake session is only valid for 4 hours. My current, temporary, solution is to restart the benthos client on a schedule. 

The gosnowflake [config ](https://pkg.go.dev/github.com/snowflakedb/gosnowflake@v1.6.6#Config) has a `KeepSessionAlive` field that I think would remedy this problem. 

Wouldn't it be nice to have this as a param in the snowflake_put config block, and add it [here](https://github.com/benthosdev/benthos/blob/547723e3ab6b49881d7f52a1e350d418080a261e/internal/impl/snowflake/output_snowflake_put.go#L563
)?

Or perhaps I'm thinking about this incorrectly and there's another way of solving my issue?

Thanks,
Niclas

**Comment by mihaitodor** [comment]
Hey @niclasgrahm, thanks for uncovering this issue! That's really annoying... Guess I didn't get to run Benthos for a long enough time to bump into this issue. According to [this](https://github.com/snowflakedb/gosnowflake/issues/477), setting `KeepSessionAlive` to `true` isn't going to help. However, as documented [here](https://github.com/snowflakedb/gosnowflake/issues/556), we'll need to set the `client_session_keep_alive` in the Config params. I raised a tentative PR [here](https://github.com/benthosdev/benthos/pull/1557) to add it. Would you mind testing this if you can clone my branch and build Benthos yourself? You can do that by installing Go 1.18+ and running `make` in the repo. It should produce the `./target/bin/benthos` binary that you can run.

**Comment by niclasgrahm** [comment]
Built it, left it sitting overnight, and now this morning shot some data at it, and it seems to work fine! I also saw that the PR has been merged :)

**Comment by mihaitodor** [comment]
Awesome, thanks for checking @niclasgrahm and glad to hear it fixed the issue! Ash rushed a bit to merge it and, thinking more about it, I'm guessing they made this "heartbeat" mechanism optional on purpose. Maybe it requires some extra permissions or smth, not sure... Would you be OK if I expose it as a config parameter which is `false` by default? I guess more people will get tripped up by this issue unless they explicitly set it to `true`, but maybe that's better than having some of them get an error up front due to missing permissions.

**Comment by niclasgrahm** [comment]
Yeah, making it an explicit parameter is probably wise. I don't know if, for example, keeping this connection alive indefinitely consumes credits on the snowflake side, so it's probably better to let people opt in to this new feature :)

again, thank you!

/N

**Comment by mihaitodor** [comment]
Sounds good. I added `client_session_keep_alive` (default `false`) in #1559.
