### ISSUE TITLE
Delay processor

### ISSUE THREAD

**Issue by webfrank** [benthosdev/benthos#1560]
Can you consider adding a simple delay processor?

There are use cases where only a delay can fix the processing. 

Something like:

delay:
  interval: 5s

**Comment by mihaitodor** [comment]
Does the [`sleep`](https://www.benthos.dev/docs/components/processors/sleep) processor help?

**Comment by webfrank** [comment]
Yes, I searched over and over but my eyes cannot find it. 

Sorry to bother. 

Thank you.
