### ISSUE TITLE
Kafka TLS: Thoughts on supporting PKCS #8 PEM private key?

### ISSUE THREAD

**Issue by mihaitodor** [benthosdev/benthos#1565]
### Discussed in https://github.com/benthosdev/benthos/discussions/1519

<div type='discussions-op-text'>

<sup>Originally posted by **dtanner** October 14, 2022</sup>
Reading [the docs](https://www.benthos.dev/docs/components/outputs/kafka#tlsclient_certspassword) for `tls.client_certs[].password`, it looks like there's a single supported encryption format of PKCS #1.  Is that correct?  If so, any plans to support other formats?  

Background:
I got a `tls: failed to parse private key` error when trying to use a password-protected, PEM-formatted PKCS8 private key as my `key_file` for a kafka output. The same file works with other tools like `kcat` and the java kafka client.  The java client doesn't support PKCS #1 😢 but does support PKCS #8 (only with passwords though!), and I'm trying to find a single compatible format for all my kafka tooling.  
I resolved the issue by using an unencrypted PKCS #8 PEM file, which does work in Benthos.  So hopefully I'm missing something, but if not I'm curious if there's anything on the roadmap for encryption support.

</div>

**Comment by mihaitodor** [comment]
Hey @dtanner, I am aware of the [github.com/youmark/pkcs8](https://github.com/youmark/pkcs8) library and I used it in another context [here](https://github.com/benthosdev/benthos/blob/97161e95c4654a30b61df1e3c530bd099a837894/internal/impl/snowflake/output_snowflake_put.go#L329-L370) but I'm really fuzzy on the various PKCS standards and encryption schemes and how to distinguish between them. In Benthos, there's some code [here](https://github.com/benthosdev/benthos/blob/97161e95c4654a30b61df1e3c530bd099a837894/internal/tls/type.go#L121-L137) which handles the `PKCS #1` format you mentioned. However, I'm not sure what's the right way to do the following:
- How to distinguish between `PKCS #1` and `PKCS #8` keys. I guess I can first call youmark's [`pkcs8.ParsePKCS8PrivateKeyRSA()`](https://pkg.go.dev/github.com/youmark/pkcs8#ParsePKCS8PrivateKeyRSA) function, which, under the hood, calls [`x509.ParsePKCS8PrivateKey()`](https://pkg.go.dev/crypto/x509#ParsePKCS8PrivateKey) and, if that spews out an error, call the existing [`x509.IsEncryptedPEMBlock()`](https://pkg.go.dev/crypto/x509#IsEncryptedPEMBlock) as fallback. If that one returns false, then assume the key is unencrypted
- How to generate valid encrypted and decrypted keys in PEM file format in both cases. I guess there are some OpenSSL magic incantations that I can use, but I could really use some help with this. If you don't know either, I'll do more digging, but it would help a lot if you can show me how to generate valid encrypted keys that are accepted by the other tools you're using.

**Comment by dtanner** [comment]
Thanks for digging into this @mihaitodor!  I'm a novice with Go so don't have a library suggestion (I spend most of my time on the JVM), but your approach sounds reasonable to me.  

For creating the various formats to test with, here are some commands to help. 
```markdown
how to create a PKCS1 key:
    
    openssl genrsa -out private.pem 2048

how to convert a PKCS1 to PKCS8 unencrypted key:

    openssl pkcs8 -topk8 -inform PEM -in private.pem -outform pem -nocrypt -out pkcs8.pem

how to convert a PKCS1 to PKCS8 encrypted key:

    openssl pkcs8 -topk8 -inform PEM -in private.pem -outform pem -out pkcs8-encrypted.pem


The first line of each private key in a file shows you the format..i.e. here's how you can tell the format of an existing file:
-----BEGIN RSA PRIVATE KEY-----       = PKCS1 unencrypted
-----BEGIN PRIVATE KEY-----           = PKCS8 unencrypted
-----BEGIN ENCRYPTED PRIVATE KEY----- = PKCS8 encrypted
```

Hope that helps - I'm happy to help where I can here.  Thanks again.

**Comment by dtanner** [comment]
A custom binary is slightly easier for me to test, but whatever's easier/faster for you - they're both easy to work with.

**Comment by mihaitodor** [comment]
Hey @dtanner, I think I have a working implementation in #1569. However, please note that we can't use keys generated by `openssl pkcs8 -topk8 -inform PEM -in private.pem -outform pem -out pkcs8-encrypted.pem` because, in this case, it uses an encryption algorithm called `pbeWithMD5AndDES-CBC` (which I think is part of the `PKCS#5` v1.5 standard) and is considered insecure (see details in the comments [here](https://stackoverflow.com/questions/54143361/what-is-pbewithmd5anddes)). I wouldn't really mind adding it for backwards compatibility, but, last time I checked, I couldn't find any pure Go library which decrypts it, given that it's considered obsolete. Thus, you'll need to use keys generated via `openssl pkcs8 -topk8 -v2 des3 -inform PEM -in private.pem -outform pem -out pkcs8-encrypted.pem` or whatever else is supported by https://github.com/youmark/pkcs8, which I believe Java should be able to decrypt as well.

If you'd like a custom binary, I think the easiest way is to [install Go](https://go.dev/doc/install) (you must use v1.18+) yourself, clone [my branch](https://github.com/mihaitodor/benthos/tree/add-pkcs8-encrypted-keys-tls-client-certs-support) and run `make` in the root of the repo. You should get a freshly-built Benthos binary under `./target/bin/benthos`.
