### ISSUE TITLE
`asdf` as an installer?

### ISSUE THREAD

**Issue by rolandtritsch** [benthosdev/benthos#1568]
Hi All, 

any plans to add support for `asdf`? 

If people think that it is a good idea (with that you can have multiple versions of `benthos` installed and can switch between them easily), I am happy to contribute a PR.

Thoughts?

**Comment by mihaitodor** [comment]
Hey @rolandtritsch, nice to see you here! 😄 That's a great idea! Would love to see Benthos among the official `asdf` [plugins](https://github.com/asdf-vm/asdf-plugins). I had a quick look over [this doc](https://github.com/asdf-vm/asdf/blob/master/docs/plugins/create.md) and I guess a separate repo is required to maintain a bunch of scripts which fetch the version list via the GitHub API. Guess it's just a fork of [this template](https://github.com/asdf-vm/asdf-plugin-template) with a new GitHub personal token. Is that what you were thinking to do?

**Comment by rolandtritsch** [comment]
Hi @mihaitodor. LOL ... good to "see" you too. Small world. Yes. That's sounds about right. Would look to "host" the repo on `benthosdev` (or I can create/host it on `rolandtritsch` or `community`). Sounds good?

**Comment by mihaitodor** [comment]
Small world indeed! ❤️  OK, I'll check with @Jeffail about getting that set up under `benthosdev`. Should be sorted early next week. I'll keep you posted.

**Comment by mihaitodor** [comment]
I created the plugin repo [here](https://github.com/benthosdev/asdf-benthos) from the template and I ran the initial `bash setup.bash` setup. The next step is to look at the TODOs and see why the build failed. Also, I have to check what GitHub personal access token needs to be created and where it needs to be set up.

**Comment by rolandtritsch** [comment]
Hi Mihai. Excellent. Happy to help/take over whenever you want/need it.

**Comment by rolandtritsch** [comment]
Hi @mihaitodor. Thanks for setting this up. I have forked the repo and have started to work on the implementation. - https://github.com/rolandtritsch/asdf-benthos

**Comment by rolandtritsch** [comment]
@mihaitodor One quick suggestion/ask: Can we/Should we rename the repo to `benthos-asdf`? Most of the other repos start with `benthos-`. Just for symmetry/consistency. Thoughts?

**Comment by mihaitodor** [comment]
Hey @rolandtritsch, thanks for jumping in! I was meaning to get to it myself, but happy to let you jump into it if you know what must be changed. I think we need to set up a token somehow, just not sure what the process is.

We can rename it, sure. My assumption was that it needs to have this name per their instructions. Let’s see if it breaks anything 😅

**Comment by mihaitodor** [comment]
Oops, forgot to update this issue. Installing Benthos via `asdf` is now possible since `v4.12.0`. The `asdf` plugin is provided in the [`benthos-asdf` repo](https://github.com/benthosdev/benthos-asdf).
