### ISSUE TITLE
Interpolate in the http payload

### ISSUE THREAD

**Issue by windmark** [benthosdev/benthos#1577]
Hi,

I'm trying to implement an ingestion for an API that paginates using `POST` and an item index in the payload. Though from what I can see, the http input/processor only supports interpolation in the URL and Header. Was it an intentional omission to not allow interpolation also in the payload? Or am I missing an obvious way of injecting a dynamic value into the payload?

Thanks for a great framework in general!

**Comment by Jeffail** [comment]
Hey @windmark, the `payload` field in the `http_client` input should support interpolation functions similar to `url` and `headers`, it looks as the documentation wasn't updated when this was implemented. The `http` processor sends the message contents as the payload so it's also dynamic but if you want to set the payload without modifying the message contents you'll need to place it within a branch processor: https://www.benthos.dev/docs/components/processors/branch#examples

**Comment by windmark** [comment]
That's awesome @Jeffail I tried it out and it works great.
