### ISSUE TITLE
Require processing only the filename

### ISSUE THREAD

**Issue by dhaldergit** [benthosdev/benthos#1586]
Hi,
I have a requirement of validating filename (naming standard, extension etc.) hence I do not need to read the content of the file. But I am able formulate the logic of validation successfully like below.
meta("path").filepath_split().index(1).has_suffix("csv") 
But this logic gets evaluated per file record count. Is it possible it run the processor per file only once.
Reference code snippet below.
input:
  broker:
    inputs:
      - resource: in_files
pipeline:
  threads: 1
  processors:
     - try:
        - resource: resource_1
        - resource: resource_2  
        - log:
             level: INFO
             message: execution start  
     - catch:
       - log:
          level: ERROR
          message: "Failed due to: ${! error() }"
       - resource: resource_3
output:
  switch:
    cases:
      - check: this.status=="ERROR"
        output:
          label: error
          processors:
            - resource: resource_4
          file:
            path: /output/${! "${ERROR_FILE_PREFIX}"}${! timestamp_unix() }.ERROR.LOG
            codec: lines

processor_resources:
        - label: resource_1
          bloblang: |
            root.filename = meta("path").filepath_split().index(1)
            root.status = "COMPLETED"
        - label: resource_2
          bloblang: |
            if (!this.filename.has_suffix("csv")  ){
               throw("File Extention is invalid")
            }
        - label: resource_3
          bloblang: |
              root.status = "ERROR"
              root.filename = meta("path").filepath_split().index(1)
              root.reason = "%s%v".format("Failed due to: ",error())
        - label: resource_4
          bloblang: |
            "FILE : %s\rREASON : %s \r\r".format(this.filename, this.reason)                    

input_resources:
  - label: in_files
    file:
      paths:
        - /input/*.*

**Comment by mihaitodor** [comment]
Hey @dhaldergit, it sounds like you'd want the `file` input to only emit one message for each file read containing only the metadata of the files. I guess we could add something like a `metadata` codec, but it will require a bit of investigation.
