### ISSUE TITLE
base64_decode execution error

### ISSUE THREAD

**Issue by Counterflowwind** [benthosdev/benthos#1587]
There is an error using base64_decode in awk processor.
the error info is:
```
level=error msg="Non-fatal execution error: illegal base64 data at input byte 43220" @service=benthos label="" path=root.pipeline.processors.2
```
my benthos.config:
```yaml
input:
  broker:
    inputs:
      - kafka:
          addresses: kafka_addrss
          topics: kafka_topic
          consumer_group: kafka_group
          sasl:
            mechanism: kafka_me
            user: kafka_user
            password: kafka_password
pipeline:
  processors:
    - protobuf:
        operator: to_json
        message: subscribe.Envelope
        import_paths: [ subscribe/subscribe.proto ]
    - awk:
        codec: "json"
        program: |
          function readfile(file, tmp, save_rs){
            save_rs = RS
            RS = "^$"
            getline tmp < file
            close(file)
            RS = save_rs

            return tmp
          }
          {
            total_value = json_get("total")
            index_type = json_type("index")
            if (index_type == "undefined") {
              json_set_int("index",0)
            }
            index_value = json_get("index")
            data_value = json_get("data")
            if (index_value == "0") {
              print data_value > "./result.json"
            } else {
              file_data = readfile("./result.json")
              gsub(/\s/,"",file_data)
              file_data = sprintf("%s%s",file_data,data_value)
              print data_value > "./result.json"
              }
            }
    - awk: 
        codec: "json"
        program: |
          function readfile(file, tmp, save_rs){
            save_rs = RS
            RS = "^$"
            getline tmp < file
            close(file)
            RS = save_rs

            return tmp
          }
          {
            data_com = readfile("./result.json")
            gsub(/\s/,"",data_com)
            decode_data = base64_decode(data_com)
            json_set("data",decode_data)
          }
    - catch: 
        - resource: error_data
    - bloblang: |
        root = this.data
    - protobuf:
        operator: to_json
        message: subscribe.Entries
        import_paths: [subscribe/subscribe.proto]
          
processor_resources:
  - label: error_data
    awk:
      codec: "json"
      program: |
        function readfile(file, tmp, save_rs){
          save_rs = RS
          RS = "^$"
          getline tmp < file
          close(file)
          RS = save_rs
          return tmp
        }
        {
          data_com = readfile("./result.json")
          gsub(/\s/,"",data_com)
          print data_com > "./err_data.json"
        }
output: 
  drop: {}
```
Why does decoding fail? My data is processed from protobuf processor.

**Comment by Jeffail** [comment]
Hey @Counterflowwind, it looks as though you should be calling `base64_encode` but I'm not sure, there's a lot of logic going on there to unpack.

**Comment by mihaitodor** [comment]
> Why does decoding fail? My data is processed from protobuf processor.

I see many operations in there before it even reaches `base64_decode`. It's really hard to tell if, indeed, that `result.json` file contains a valid base64-encoded string. To narrow it down, I suggest you insert a `log` processor between the `protobuf` one and the first `awk` one and then, after you capture one of those messages, replace your input with a `generate` input which simply produces the data from the JSON you captured. That way, you'll have an easily-reproducible example to play with and share with us if you still need help.

Additionally, it seems to me like a lot of the logic which is done via `awk`, if not all of it, would be way more maintainable if expressed via bloblang using `mapping` processors. Have you found some limitations in bloblang which prevent you from using it? Also, storing state to disk in those json files via `awk` makes things way more difficult than they should be. Have you considered using a [cache](https://www.benthos.dev/docs/components/caches/about) instead? Also, if it's something related to the current message, [metadata](https://www.benthos.dev/docs/configuration/metadata/) is getting [support](https://github.com/benthosdev/benthos/issues/1558) for structured data in the next release, which can simplify things a lot.

Another thing to keep in mind is that if any of the processors fails, you can inspect the error in a `log` processor using `message: ${! error() }`. The `error()` function is documented [here](https://www.benthos.dev/docs/guides/bloblang/functions#error).
