### ISSUE TITLE
Deadlock when benthos trying to connect to websocket endpoint

### ISSUE THREAD

**Issue by diptomondal007** [benthosdev/benthos#1595]
It seems there is a deadlock when benthos is trying to reconnect to a dynamic WebSocket input endpoint, DELETE/POST doesn't work in inputs endpoint and it takes infinite time.
Benthos Log-
```
time="2022-12-03T06:43:52Z" level=error msg="Failed to connect to websocket: malformed ws or wss URL" @service=benthos label="" path=root.input.dynamic.inputs.a612d0dc-f826-4617-a11d-b89d1d623037
```
I think it can't acquire a lock on `configHashes` [Here](https://github.com/benthosdev/benthos/blob/main/internal/api/dynamic_crud.go#L246).

**Comment by Jeffail** [comment]
Hey @diptomondal007, I tried to reproduce this with the following config:

```yaml
http:
  enabled: true
  debug_endpoints: true

input:
  dynamic: {}
```

And then these commands:

```sh
curl -X POST http://localhost:4195/inputs/foo -d '{"websocket":{"url":"ws2://localhost:4195"}}'
curl -X DELETE http://localhost:4195/inputs/foo
```

But I don't get the deadlock so there's something missing. Which version of Benthos are you running? And is there anything else going on in your config that might be related?

**Comment by diptomondal007** [comment]
I am using version `4.1.0`. I have port-forwarded and tried `curl -X POST http://localhost:4195/inputs/foo -d '{"websocket":{"url":"ws2://localhost:4195"}}'`. But it's stuck. But it seems the `foo` config was added. Now the pod log is -
```
time="2022-12-03T10:16:30Z" level=error msg="Failed to connect to websocket: malformed ws or wss URL" @service=benthos label="" path=root.input.dynamic.inputs.foo
time="2022-12-03T10:16:30Z" level=error msg="Failed to connect to websocket: dial tcp 34.142.48.9:443: i/o timeout" @service=benthos label="" path=root.input.dynamic.inputs.a612d0dc-f826-4617-a11d-b89d1d623037
```
And `curl -X DELETE http://localhost:4195/inputs/foo` this request got stuck too and not deleting the config

**Comment by diptomondal007** [comment]
Can't see this issue in the latest version though. It's fixed I think

**Comment by Jeffail** [comment]
Okay thanks @diptomondal007, I'll close this for now but if you see it again then please reopen and we can dig a little more.
