### ISSUE TITLE
Add array concatenation

### ISSUE THREAD

**Issue by greysond** [benthosdev/benthos#1632]
I've been writing quite a lot of bloblang in the last couple of months and I've found that some method of concatenating arrays would be extremely helpful. Right now I'm using `[arr1, arr2, arr3].flatten()` quite a bit, but I would greatly prefer something like `arr1 + arr2 + arr3` or maybe even `arr1.concat(arr2, arr3)`.

**Comment by mihaitodor** [comment]
Here's a workaround using the `fold()` method, but I agree that it should be more intuitive:

```coffee
let lhs = [1,2,3]
let rhs = [4,5,6]
root = $rhs.fold($lhs, k -> k.tally.append(k.value))
```

**Comment by Jeffail** [comment]
Finally got around to this: https://github.com/benthosdev/benthos/commit/3310065cf97944a8545563187997cc47e409fa92
