### ISSUE TITLE
Custom processors

### ISSUE THREAD

**Issue by natenho** [benthosdev/benthos#1637]
It would be great to allow extending Benthos with custom golang processors. I have not found any mention to that in docs.

**Comment by Jeffail** [comment]
Hey @natenho yep there's a plugin API, the gopkg docs are here: https://pkg.go.dev/github.com/benthosdev/benthos/v4@v4.11.0/public/service
There's also an example repo: https://github.com/benthosdev/benthos-plugin-example
And it's a bit out of date but there's also a video walkthrough: https://www.youtube.com/watch?v=uH6mKw-Ly0g

**Comment by natenho** [comment]
@Jeffail thank you! I've also found this https://www.benthos.dev/blog/2019/08/20/write-a-benthos-plugin/
So it might be interesting to move some links to the Docs (https://www.benthos.dev/docs/about), its kinda hidden inside the blog post, and it might be a good way to let people know how flexible it can get!
