### ISSUE TITLE
GCP Pubsub Output - Ability to set options to the NewClient for pubsub publish

### ISSUE THREAD

**Issue by pradeeppattamatta** [benthosdev/benthos#1638]
Can we provide ability to add `ClientOption`s when building  `NewClient` in output_pubsub flow? I am mainly looking at the option of setting the endpoint to a region specific pubsub endpoint. If providing the ability to some of those supported options is not recommended or going to be a breaking change, can we provide option to add specific ones as config like endpoint etc.. ?

File that needs to be changed: https://github.com/benthosdev/benthos/blob/48c7bb7a0718bdcef453cc156f60f2ffafb48730/internal/impl/gcp/output_pubsub.go#L101

Google Pubsub library doc related to Client Option: 
https://pkg.go.dev/cloud.google.com/go/pubsub#NewClient
https://pkg.go.dev/google.golang.org/api/option#ClientOption

**Comment by mihaitodor** [comment]
Hey @pradeeppattamatta, thanks for digging into this! It looks like a simple enhancement if you only care about the endpoint for now. Basically, one would have to add `endpoint` as an optional string field and call [`WithEndpoint()`](https://pkg.go.dev/google.golang.org/api/option#WithEndpoint) on it if it's present. The same change would need to be made to the input [here](https://github.com/benthosdev/benthos/blob/48c7bb7a0718bdcef453cc156f60f2ffafb48730/internal/impl/gcp/input_pubsub.go#L119) too.

Happy to accept a PR for it if you're interested in submitting one. After changing the relevant `.go` files, the documentation `.md` files can be regenerated via `make docs`.
