### ISSUE TITLE
Can't find bethos.studio source code

### ISSUE THREAD

**Issue by shovael** [benthosdev/benthos#1643]
I'm trying to start using benthos on a closed private network, and I can't find the source code for benthos.studio

**Comment by mhite** [comment]
See https://www.benthos.dev/blog/2022/11/07/whats-next/

> You may also have noticed that Benthos Studio is not open source. This is because I believe Studio is a good bet at putting together a scalable monetisation strategy that complements the goals of the open source work rather than causing friction against it, a sort of golden path for building a business around an existing open source ecosystem. It will take a while to work out which features should be paid for, but there will always be a free tier that provides all the interesting bits.
