### ISSUE TITLE
http_server and unarchive - how to split message into individual messages

### ISSUE THREAD

**Issue by fundef1** [benthosdev/benthos#1652]
Hi, 
I think I'm missing something wrt batching vs messages but I can't get the following to work:

my use case: post a file over http and handle each line. 
It's really a headerless CSV I wanted to parse_csv line by line  but narrowed it down.

my trimmed config.yaml
```
input:
  label: "http_post"
  http_server:
    address: ""
    path: /post
    allowed_verbs:
      - POST
pipeline:
  threads: 1
  processors:
    - label: "split_by_linefeed"
      unarchive:
        format: lines
output:
  label: "stdout"
  stdout:
    codec: lines
```
my test2.csv
```
line,1
line,2
line,3
line,4
```
 curl
```
curl -X POST -d @./test2.csv http://127.0.0.1:4195/benthos/post
```
response from benthos:  
```
INFO Running main config from specified file       @service=benthos path=config.yaml
INFO Launching a benthos instance, use CTRL+C to close  @service=benthos
INFO Listening for HTTP requests at: http://0.0.0.0:4195  @service=benthos
TRAC Consumed 1 messages from POST to '/post'.     @service=benthos label=http_post path=root.input
TRAC Attempting to write 1 messages to 'stdout'.   @service=benthos label=stdout path=root.output
line,1line,2line,3line,4
TRAC Successfully wrote 1 messages to 'stdout'.    @service=benthos label=stdout path=root.output
```
consumer 1 message from post is correct but
I was expecting four lines, i.e. four messages from stdout

What am I doing wrong here?
thanks for any help or pointers in the right direction.

**Comment by mihaitodor** [comment]
Hey @fundef1, the `-d` (aka `--data`) curl flag has some special semantics. Try replacing it with `--data-binary`. See the docs [here](https://curl.se/docs/manpage.html#-d):

> When [-d, --data](https://curl.se/docs/manpage.html#-d) is told to read from a file like that, carriage returns and newlines will be stripped out.

**Comment by fundef1** [comment]
🤦‍♂️
thanks! that solved it.
