### ISSUE TITLE
How to get a substring in bloblang

### ISSUE THREAD

**Issue by natenho** [benthosdev/benthos#1653]
Hi! How can I extract a substring using bloblang?

Example: 
Given input "FooBar" 
Expected output "Bar"

It is a trivial function that I could not find in the list of string manipulation methods. If it does not exist, is there any alternative?

**Comment by Jeffail** [comment]
Hey @natenho, there's a slice method for chopping strings via low/high indexes: https://www.benthos.dev/docs/guides/bloblang/methods#slice, but there's also a regular expression replace method for more complex stuff: https://www.benthos.dev/docs/guides/bloblang/methods#re_replace_all

**Comment by natenho** [comment]
@Jeffail  Thanks again for patientily answering my stupid question ... I swear I checked twice before opening this one.
Hopefully it can be useful as a keyword for someone looking for the same thing :-)
