### ISSUE TITLE
resource execution order

### ISSUE THREAD

**Issue by dhaldergit** [benthosdev/benthos#1689]
Hi @Jeffail ,

Is there any way to maintain a fixed order of resource execution. The resources in below code snippet are getting executed in random order. Please support. Thanks 

output:
  switch:
    strict_mode: true
    cases:
      - check: meta("path").filepath_split().index(1).has_prefix("${CUST_FILE_PREFIX}")
        continue: false
        output:
          broker:
            outputs:
              - resource: customer_acct_out_dt  # order 1
              - resource: customer_acct_out_ct  # order 2 i.e after 1

**Comment by Jeffail** [comment]
@dhaldergit you can specify `fan_out_sequential` as a broker pattern: https://www.benthos.dev/docs/components/outputs/broker#fan_out_sequential
