### ISSUE TITLE
subprocess executed without any input

### ISSUE THREAD

**Issue by antonio-antuan** [benthosdev/benthos#1737]
Looks like subprocess processor executed immediatelly without any input. Doesn't matter if it's inside of `input` or `pileline` section.

I'm trying to use this version, just installed with `curl -Lsf https://sh.benthos.dev | bash`:
```
Version: (devel)
Date: 2022-12-21T18:56:52Z
```

```
Operating System: Arch Linux                      
 Kernel: Linux 6.1.9-arch1-1
```

config is pretty simple:
```
input:
  stdin:
    codec: lines
  processors:
    - mapping: root = content().uppercase()


pipeline:
  processors:
    - subprocess:
        name: echo

logger:
  level: ALL
  format: logfmt
  add_timestamp: true
  timestamp_name: time

```

I run `benthos -c config.yaml`, don't provide any input, just start the process. 
Immediatelly logs appear:
```
➜  scribe git:(develop) ✗ benthos -c config.yaml 
INFO[2023-02-09T17:01:46+02:00] Running main config from specified file       @service=benthos path=config.yaml
INFO[2023-02-09T17:01:46+02:00] Subprocess started                            @service=benthos label="" path=root.pipeline.processors.0
INFO[2023-02-09T17:01:46+02:00] Launching a benthos instance, use CTRL+C to close  @service=benthos
INFO[2023-02-09T17:01:46+02:00] Listening for HTTP requests at: http://0.0.0.0:4195  @service=benthos
WARN[2023-02-09T17:01:46+02:00] Subprocess exited                             @service=benthos label="" path=root.pipeline.processors.0
ERRO[2023-02-09T17:01:46+02:00] Failed to read subprocess output: read |0: file already closed  @service=benthos label="" path=root.pipeline.processors.0
INFO[2023-02-09T17:01:46+02:00] Subprocess started                            @service=benthos label="" path=root.pipeline.processors.0
WARN[2023-02-09T17:01:46+02:00] Subprocess exited                             @service=benthos label="" path=root.pipeline.processors.0
ERRO[2023-02-09T17:01:46+02:00] Failed to read subprocess output: read |0: file already closed  @service=benthos label="" path=root.pipeline.processors.0
INFO[2023-02-09T17:01:46+02:00] Subprocess started                            @service=benthos label="" path=root.pipeline.processors.0
WARN[2023-02-09T17:01:46+02:00] Subprocess exited                             @service=benthos label="" path=root.pipeline.processors.0
ERRO[2023-02-09T17:01:46+02:00] Failed to read subprocess output: read |0: file already closed  @service=benthos label="" path=root.pipeline.processors.0
INFO[2023-02-09T17:01:46+02:00] Subprocess started                            @service=benthos label="" path=root.pipeline.processors.0
WARN[2023-02-09T17:01:46+02:00] Subprocess exited                             @service=benthos label="" path=root.pipeline.processors.0
ERRO[2023-02-09T17:01:46+02:00] Failed to read subprocess output: read |0: file already closed  @service=benthos label="" path=root.pipeline.processors.0
INFO[2023-02-09T17:01:46+02:00] Subprocess started                            @service=benthos label="" path=root.pipeline.processors.0
WARN[2023-02-09T17:01:46+02:00] Subprocess exited                             @service=benthos label="" path=root.pipeline.processors.0
ERRO[2023-02-09T17:01:46+02:00] Failed to read subprocess output: read |0: file already closed  @service=benthos label="" path=root.pipeline.processors.0
...
```

What do I do wrong?

**Comment by mihaitodor** [comment]
Hey @antonio-antuan, I believe this is covered in #1734.

**Comment by antonio-antuan** [comment]
understood, thanks.
just to clarify: what is the reason of this behavior? why do I have to wrap all subprocess calls?

**Comment by antonio-antuan** [comment]
Another question: I want to put json data as an input. Looks like I can't use benthos interpolation inside of script, right? So I have to use jq inside of EACH wrapper... doesn't looks very convenient. Is there any other way to execute subprocesses without wrapper?

**Comment by mihaitodor** [comment]
> just to clarify: what is the reason of this behavior? why do I have to wrap all subprocess calls?

The `subprocess` components are meant for long-running processes which don't shut down after processing one message. The goal is to avoid the penalty of having them start up and shut down for each message. However, some people find this behaviour surprising since they just want to run some quick script for each message. While these components could be enhanced to support this pattern, the wrapper I provided is a usable workaround for now.

> Another question: I want to put json data as an input. Looks like I can't use benthos interpolation inside of script, right? So I have to use jq inside of EACH wrapper... doesn't looks very convenient. Is there any other way to execute subprocesses without wrapper?

You lost me... What do you mean "put json data as an input"? Do you want to read a JSON document from a file? That's well-supported by using the `file` input with `codec: all-bytes`. I don't get why you believe you need to invoke `jq`. Benthos has this builtin DSL called Bloblang (see docs [here](https://www.benthos.dev/docs/guides/bloblang/about)) which should cover most of the JSON document transformations that `jq` can do. Also, it can attempt to parse arbitrary strings as JSON if needed (see the [`parse_json()` method](https://www.benthos.dev/docs/guides/bloblang/methods#parse_json)).
