### ISSUE TITLE
Fail when env vars are unset?

### ISSUE THREAD

**Issue by wpcarro** [benthosdev/benthos#1749]
Would you accept a pull request if I made one?

Would be nice to fail on initialization when a pipeline definition references an environment variable that is unset. I'm assuming this doesn't already exist, but I'm a benthos noob, so please lmk it's quite likely I'm wrong.

**Comment by wpcarro** [comment]
An illiterate programmer's attempt at supporting this. Basically I'm not sure how to pass around the configuration and apply the `c.Bool("strict-env")` value to the `ReplaceEnvVariables` call. The good news is that in some local tests, `ReplaceEnvVariables` works as expected (when the condition is hard-coded):

https://github.com/benthosdev/benthos/pull/1750

**Comment by Jeffail** [comment]
Hey @wpcarro, sure that sounds useful. I'd actually maybe suggest this should have been made the default from the beginning, but having a separate cli flag is a good compromise for now.

**Comment by wpcarro** [comment]
> Hey @wpcarro, sure that sounds useful. I'd actually maybe suggest this should have been made the default from the beginning, but having a separate cli flag is a good compromise for now.

Great to hear :) I have a half-baked PR (#1750) that I can finish-up once I determine how to thread the CLI config to downstream functions (I'm a golang noob, so it's a bit awkward).
