### ISSUE TITLE
Batch metrics are populated even if we don't use batching

### ISSUE THREAD

**Issue by narzdavid** [benthosdev/benthos#1762]
Is it normal that we see metrics for batching even though we don't use batching in any of our streams? We see the following with positive numbers for the ff. metrics:

- processor_batch_received
- processor_batch_sent
- output_batch_sent
 

In the case that batching is not used, what do the numbers above mean?

**Comment by Jeffail** [comment]
Hey @narzdavid, yeah they're standard metrics, in your case each message is processed as a batch of size one.

**Comment by narzdavid** [comment]
Thanks for the clarification! :)
