### ISSUE TITLE
kafka_franz output does not have the partition and key attributes that the standard kafka output does

### ISSUE THREAD

**Issue by dehuszar** [benthosdev/benthos#1796]
We are currently using the kafka_franz input as part of a topic migration effort.  One of the aspects of Benthos that has been helpful to us on the service/consumer side is the ability of the standard kafka output component to [explicitly assign which partition to use](https://www.benthos.dev/docs/components/outputs/kafka#partition) when writing to the output topic.

Unfortunately, the `kafka_franz` output does not have this argument yet.  If this piece of functionality were ported over from the standard output, it would be much appreciated.

**Comment by dehuszar** [comment]
This looks to be resolved by [4.13.0](https://github.com/benthosdev/benthos/blob/main/CHANGELOG.md#4130---2023-03-15), no?

**Comment by Jeffail** [comment]
Hey @dehuszar, yep 😅 thanks for the heads up.
