### ISSUE TITLE
Convert json.Number to Float64

### ISSUE THREAD

**Issue by webfrank** [benthosdev/benthos#1801]
Hi,
  I was trying to insert data into Clickhouse table with a Float64 field but I got this error:

converting json.Number to Float64 is unsupported

Probably .float32() and .float64() are also needed.

**Comment by Jeffail** [comment]
Hey @webfrank yeah there's a bunch of number conversion methods now: https://www.benthos.dev/docs/guides/bloblang/methods#number-manipulation

**Comment by webfrank** [comment]
Hi, I've seen the conversions but float are missing.
