### ISSUE TITLE
Date formatting utilities

### ISSUE THREAD

**Issue by webfrank** [benthosdev/benthos#1803]
Hi,
  I want to store a Date Object in Mongo for the now() timestamp.

If I use directly now() I got a string, if I add a ts_format() I correctly end up with a string, I manages to save a Date object with this:

now().ts_format("2006-01-02T15:04:05Z", "UTC").ts_parse("2006-01-02T15:04:05Z")

Probably and easier way to do this? Should now() return a time object directly?

**Comment by peczenyj** [comment]
did you try `now().ts_unix()` ?

**Comment by webfrank** [comment]
Hi, it returns a long, not a date in Mongo

**Comment by mihaitodor** [comment]
Does calling [`ts_tz`](https://www.benthos.dev/docs/guides/bloblang/methods#ts_tz) help?

**Comment by Jeffail** [comment]
Yeah calling `now().ts_tz("UTC")` is probably the easiest approach. I believe `now()` was left as is for backwards compatibility when we added the new timezone functionality so we can't really change it.
