### ISSUE TITLE
cached processor with deleted() 

### ISSUE THREAD

**Issue by praetorian-thendrickson** [benthosdev/benthos#1804]
I noticed that when using a `cached` processor if one of the `cached` child processors errors and deletes (drops) the message, benthos will error with a message saying: `Child processors failed: child processors resulted in zero messages`. For example, use this config and input:
```json
{ "question": "what is the best stream processing pipeline?", "answer": "benthos" }
```

```yaml
cache_resources:
  - label: dedupe
    memory:
      init_values: {}
input:
  stdin:
    codec: lines
pipeline:
  threads: 1
  processors:
    - branch:
        processors:
          - cached:
              key: 'dedupe::${! this.question }'
              cache: dedupe
              processors:
                # mocking root = if errored() { deleted() }
                - bloblang: root = deleted()
output:
  stdout:
    codec: lines
```

Will result in this output:
```
INFO Running main config from specified file       @service=benthos path=config.yaml
INFO Launching a benthos instance, use CTRL+C to close  @service=benthos
ERRO Child processors failed: child processors resulted in zero messages  @service=benthos label="" path=root.pipeline.processors.0
INFO Listening for HTTP requests at: http://0.0.0.0:4195  @service=benthos
{ "question": "what is the best stream processing pipeline?", "answer": "benthos" }
INFO Pipeline has terminated. Shutting down the service  @service=benthos
```

What's the right way to drop a message under the cached processor (like on an error)? Is the `child processors resulted in zero messages` error expected in this case? Thanks!

**Comment by Jeffail** [comment]
hey @praetorian-thendrickson, what's the branch processor there for? As I'm fairly sure that's where the problem is, a branch processor needs the number of messages to align at the end of the child processors. Also you don't need a `cached` processor for deduplication as there's a specific processor for that: https://www.benthos.dev/docs/components/processors/dedupe

**Comment by disintegrator** [comment]
Hey @praetorian-thendrickson can you take a look at this PR and let me know if it address your issue?
https://github.com/benthosdev/benthos/pull/1821

**Comment by praetorian-thendrickson** [comment]
Hey @disintegrator, that looks like it will address it! Thank you for the pr work 👍
