### ISSUE TITLE
Gets data for each step of the component's execution

### ISSUE THREAD

**Issue by gaoshenga** [benthosdev/benthos#1896]
Can the benthos component monitor the data being processed at each step? Similar to the input component fetching the data and then processing the transformation, you can present the data at each step.

**Comment by Jeffail** [comment]
Hey @gaoshenga you can get info like that either through tracing https://www.benthos.dev/docs/components/tracers/about, or there's also https://studio.benthos.dev/ that gives a bunch of visualisation goodies (more coming soon) for Benthos configs.
