### ISSUE TITLE
No apis for resources update and delete in Streams rest apis

### ISSUE THREAD

**Issue by piyushmbm45** [benthosdev/benthos#1900]

**Comment by Jeffail** [comment]
@piyushmbm45, you can update existing resources by POSTing a new config: https://www.benthos.dev/docs/guides/streams_mode/streams_api#post-resourcestypeid. We might support deleting in future, but don't right now as it has the potential to lock up streams when they have remaining dependents, but you can update resources to provide a no-op behaviour.

**Comment by piyushmbm45** [comment]
thanks for reply @Jeffail.
thats right for deleting.
please get api so that we can see which resources are deployed
