### ISSUE TITLE
Logger not recognized, whenever i use Stream rest apis

### ISSUE THREAD

**Issue by piyushmbm45** [benthosdev/benthos#1904]

**Comment by Jeffail** [comment]
Hey @piyushmbm45, the logger isn't part of a stream config:

> When running Benthos in streams mode it is still necessary to provide a general service wide configuration with the `-c/--config` flag that specifies observability configuration such as the `metrics`, `logger` and `tracing` sections, as well the `http` section for configuring how the HTTP server should behave.

From https://www.benthos.dev/docs/guides/streams_mode/about

**Comment by piyushmbm45** [comment]
When it will be part of it
