### ISSUE TITLE
Add protobuf schema support to`schema_registry_encode` / `schema_registry_decode`

### ISSUE THREAD

**Issue by ye11ow** [benthosdev/benthos#1906]
Similar to #1150 , we can add protobuf schema support for these two functions as well.
More details: https://docs.confluent.io/platform/current/schema-registry/fundamentals/serdes-develop/index.html#wire-format

Sample code from kafka-go-client: https://github.com/confluentinc/confluent-kafka-go/blob/master/schemaregistry/serde/protobuf/protobuf.go#LL347C34-L347C34

**Comment by ye11ow** [comment]
Hi @Jeffail , I already have some working code on our repo, should be able to create a PR for limited protobuf decode support

**Comment by Jeffail** [comment]
Hey @ye11ow, this'd be awesome! I have limited availability for the next few weeks but I'll review the open PR ASAP.

**Comment by ye11ow** [comment]
Thank you @Jeffail for the excellent work on this!

**Comment by Jeffail** [comment]
Done via: https://github.com/benthosdev/benthos/commit/cb07600d5ccb0e1ac7399cdcb10e085d6c4aeab4
And: https://github.com/benthosdev/benthos/commit/a3d52e2428e6c33f26cf14435ec0a585ff2f8e7e
