### ISSUE TITLE
csv component problem

### ISSUE THREAD

**Issue by gaoshenga** [benthosdev/benthos#1907]
I found that using the csv component, using the parse header information to read the csv file. The read result is a json file
```
{"header2":"bar2","header3":"bar3","·﻿header1":"bar1"}
```
"head1" is the first column, and the "head1" field is preceded by a small red dot.
 To the next processing
```
root.test = this.head1
```
The value of the "test" field is null,

Is there any way to get the field value of the first column?

**Comment by dcb9** [comment]
**.header1** field has a special character DOT, to access it you should add quotes according to the doc, [Special Characters in Paths]( https://www.benthos.dev/docs/guides/bloblang/about#special-characters-in-paths)

~~~
root.test = this.".header1"
~~~

**Comment by gaoshenga** [comment]
For example, a csv file
```
aa,id,name,age,sex,tel,namekey
0,1,zhangsan,11,1,18766665555,jaja
```
Using the benthos csv component, you read:
```
{"age":"12","id":"2","name":"lisi","namekey":"haha","sex":"1","tel":"18766665555","﻿aa":"1"}
```

I want to change the aa field name to AA, using the following mapping language:
```
root.AA = this.aa or root.AA = this.".aa"
```

The result is still null
   AA = null

I wonder if there is a problem with using the csv component. I have done a lot of experiments and this problem occurs when working with the first column of the csv file.

**Comment by Jeffail** [comment]
Hey @gaoshenga, which version of benthos are you running? With the latest if I run that example config with the mapping `root.AA = this.aa` it works fine.

**Comment by gaoshenga** [comment]
Version: 4.13.0
