### ISSUE TITLE
int8(), uint8(), int16(), uint16() support for mapping

### ISSUE THREAD

**Issue by packman80** [benthosdev/benthos#1910]
It is especially important for clickhouse (and other dbms) to support additional data types (int8, uint8, uint16, int16), as they are actively used. Especially uint8, as it is needed to replace Boolean data types

**Comment by Jeffail** [comment]
Also might as well add `float32` and `float64` while we're at it.

**Comment by dedot271** [comment]
This is our blocking task to introduce benthos into our prod. There are a lot of uint8/16 type columns made for optimization. @Jeffail: Is it possible to hope that this task will be done in the nearest future ?

**Comment by Jeffail** [comment]
@dedot271 I can't give you an ETA, if you want to speed things up but can't implement this yourselves then sponsorship would be an option: https://www.benthos.dev/support

**Comment by AlejandroUPC** [comment]
Hey I am really interested in this but I can't yet write good enough go, is there a workaround for this?
At the moment it's impossible to insert datatypes such as float into clickhouse

**Comment by hyingreborn** [comment]
With the same problem, I can't change the data type of clickhouse. I hope this problem will be given a higher priority.

**Comment by zer0stars** [comment]
Seconding need for this!

**Comment by Jeffail** [comment]
Done: https://github.com/benthosdev/benthos/commit/773d1c128bf1493cfd7304d72137f7da27e74c7f
