### ISSUE TITLE
nats input - default "prefetch_count" configuration too low

### ISSUE THREAD

**Issue by ahuret** [benthosdev/benthos#1912]
Hello, first of all, thanks a lot for this very nice tool !
We moved from https://github.com/nats-io/nats-kafka to benthos for both nats to kafka and kafka to nats purpose and the migration has been very easy and straightforward !

While implementing nats to kafka direction, we had issue with slow consumers, which is a known issue (see https://docs.nats.io/using-nats/developer/connecting/events/slow).
By updating the `prefetch_count` from default value (32) to an higher one (100 000) this issue stopped.
I did some research especially to know what would be a good value (of course it depends on the use case) and found that nats use `512 * 1024`  (see https://github.com/nats-io/nats.go/blob/v1.25.0/nats.go#L4662) as default in golang client library, so I was thinking we could use the same as benthos default instead of the `32` value which is very low in my opinion.

We could use the public variable `DefaultSubPendingMsgsLimit` as default, what do you think ?

**Comment by Jeffail** [comment]
Hey @ahuret, sure that sounds reasonable to me.
