### ISSUE TITLE
no such file or directory for mounted secrets in container

### ISSUE THREAD

**Issue by thilagak** [benthosdev/benthos#1913]
Hi,

I am using docker volume to mount secret files into container volume and accessing it using the environment variable. Benthos process alway reports "no such file or directory" error though the files exist with right permissions and I am able to run system commands like ls, etc., on those files. Have no clue what could be the issue.

Greatly appreciate any help.

Regards
Thilaga

**Comment by Jeffail** [comment]
Hey @thilagak, are you able to share some sort of reproducible example? Otherwise all we can do is speculate on our side.

**Comment by thilagak** [comment]
Hi @Jeffail ,

I have all my secrets in relative path of ./certificates folder and below is my docker run:
docker run -d --rm -p 4195:4195 -v certificates:/etc/secrets --env-file ./env.list --name <NAME> benthos -c /pipeline/config.yaml

But benthos reports "no such file or directory" though i see the files exist inside container with read/execute permissions.

Please let me know if you need more details.

**Comment by mihaitodor** [comment]
> I have all my secrets in relative path of ./certificates folder and below is my docker run:
> docker run -d --rm -p 4195:4195 -v certificates:/etc/secrets --env-file ./env.list --name benthos -c /pipeline/config.yaml

Docker volume mounts don't work with relative paths. See [here](https://github.com/moby/moby/issues/4830) and [here](https://stackoverflow.com/questions/51312276/docker-how-to-pass-a-relative-path-as-an-argument) for workarounds. Something like `-v $(pwd)/certificates:/etc/secrets` should do the trick.

**Comment by mihaitodor** [comment]
@thilagak No worries! Can you please check again and maybe share more details? I don't see how `/pipeline/config.yaml` ends up in the container in the first place from the `docker` command you shared. Are you creating a custom container?
