### ISSUE TITLE
Extensions to the logging and metrics plug-in

### ISSUE THREAD

**Issue by gaoshenga** [benthosdev/benthos#1920]
Hey, I see no examples of logging and metrics on this plugin page [https://pkg.go.dev/github.com/benthosdev/benthos/v4@v4.11.0/public/service#example-package-StreamBuilderConfig](url)  . Does benthos provide logging and metrics?

Could you give me examples of logging and metrics plugins?

**Comment by Jeffail** [comment]
Hey @gaoshenga, you can set any of the existing metrics/logging outputs via config:
https://pkg.go.dev/github.com/benthosdev/benthos/v4@v4.15.0/public/service#StreamBuilder.SetMetricsYAML
https://pkg.go.dev/github.com/benthosdev/benthos/v4@v4.15.0/public/service#StreamBuilder.SetLoggerYAML
Or set a custom logger:
https://pkg.go.dev/github.com/benthosdev/benthos/v4@v4.15.0/public/service#StreamBuilder.SetPrintLogger

And you can also register metrics output plugins: https://pkg.go.dev/github.com/benthosdev/benthos/v4@v4.15.0/public/service#RegisterMetricsExporter

**Comment by gaoshenga** [comment]
Hello, do you have examples of these methods? I can refer to it

**Comment by Jeffail** [comment]
Unfortunately not to hand, there might be some repos out in the wild if you search for the method signatures.
