### ISSUE TITLE
Mutated input value not reaching output sink if processors are used

### ISSUE THREAD

**Issue by thilagak** [benthosdev/benthos#1922]
Hi,

I use Benthos to consume messages and use mutation on some of the input data and want that to be passed over to output sink. The mutated data is passed over to the output if I am not using any other processor but I do have one http processor in the pipeline. Once the http processor is executed it replaces the root object from http processor response payload which makes me loose my mutated data.

I may be missing something but it will be great help if anybody can guide me how to handle this scenario.

**Comment by mihaitodor** [comment]
Hey @thilagak, there are multiple ways to address this. For example, you could do the following:
- Use a [branch processor](https://www.benthos.dev/docs/components/processors/branch) to wrap the `http` one
- Place the mutated object in the [metadata](https://www.benthos.dev/docs/configuration/metadata)

**Comment by thilagak** [comment]
Yes I do use branch processor to wrap the http. Tried the mutated object in metadata too. But let me try validate again if I used them correctly.

**Comment by thilagak** [comment]
Previously I tried put in headers and read from metadata but doing below helped resolve the issue.

    - mutation: |
        meta id = this.id

Thanks a lot @mihaitodor .
