### ISSUE TITLE
Linting with Environment Variables includes commented out variables

### ISSUE THREAD

**Issue by jc43081** [benthosdev/benthos#1931]
The lint command is failing with "required environment variables were not set" even though line with the environment variable is commented out using '#'. My expectation is commented lines should be ignored by the linter.

**Comment by Jeffail** [comment]
Hey @jc43081, unfortunately environment variable interpolations are done before the YAML is parsed out. This is a deliberate decision originally made as the interpolations themselves could potentially change the YAML structure itself, but we could maybe revisit that. However, for now you can disable this particular linting rule with `benthos lint --skip-env-var-check`.
