### ISSUE TITLE
How to handle errors when output fails, and send custom sync_response payload?

### ISSUE THREAD

**Issue by mannharleen** [benthosdev/benthos#1932]
Requirement (as simple as it sounds, I am scratching my head):
- upon successfully writing data into sqlserver, send a sync_response with body = `{"status": "success"}`
- if sqlserver output fails, send a sync_response with body = `{"status": "errored"}`

I have gone through [this example issue](https://github.com/benthosdev/benthos/issues/740#issuecomment-821246279) but it uses `try` inside output that is not supported by benthos v4.15.0 (latest).

How can I get this going? 
I have tried combining switch, fallback and broker but unable to arrive at the required solution.

**Comment by mihaitodor** [comment]
Hey @mannharleen, the `try` broker was replaced with `fallback` in commit f79350030. If you look at the [`sync_response` output](https://www.benthos.dev/docs/components/outputs/sync_response) example, it uses a `broker` output with `pattern: fan_out`. You can either use the `fallback` output or change the `pattern` to `fan_out_sequential`. I guess you're bumping into #1210, but not sure if any of the comments there will help you find a solution if you're running into connectivity issues
