### ISSUE TITLE
Support ability to launch Benthos programmatically with command line arguments

### ISSUE THREAD

**Issue by josephwoodward** [benthosdev/benthos#1940]
Currently we use the [`StreamBuilder`](https://pkg.go.dev/github.com/Jeffail/benthos/v3/public/service#Environment.NewStreamBuilder) API to launch Benthos programmatically, however due to it not supporting [Streams Mode](https://www.benthos.dev/docs/guides/streams_mode/about) we've decided to look at launching Benthos programmatically via the [`service.RunCLI`](https://github.com/benthosdev/benthos/blob/v4.16.0/public/service/service.go#L23-L25) command, which eventually makes the following call to pass arguments via `os.Args`:

```golang
func Run(ctx context.Context) {
    _ = App().RunContext(ctx, os.Args)
}
```

However it doesn't appear to be possible to set `os.Args` to pass the necessary configuration.

Would you be open to a PR for adding an additional function such as:

```golang
func RunCLIWithArgs(ctx context.Context, arguments []string) (err error) {
    ...
}
```

**Comment by Jeffail** [comment]
Hey @josephwoodward, I actually added this recently in a new `servicetest` package: https://pkg.go.dev/github.com/benthosdev/benthos/v4@v4.16.0/public/service/servicetest#RunCLIWithArgs, the intention was to add helpful functions for unit tests but it'd also solve your use case here.

**Comment by josephwoodward** [comment]
@Jeffail Oh great! I didn't see that there. Is there any reason for it to live in the `servicetest` package? It seems quite valuable to be in the `service` package, and avoids any questions around using it for production purposes.
