### ISSUE TITLE
Problems with the http_client setup

### ISSUE THREAD

**Issue by gaoshenga** [benthosdev/benthos#1943]
Hey, the http_client component on benthos executes continuously when benthos is started, and I want the http_client component to execute only once. How can I configure the http_client component?

**Comment by Jeffail** [comment]
Hey @gaoshenga, there's two options. One is to use a generate input with the count set to one followed by an http processor. The second option is to wrap the http_client input within a read_until: https://www.benthos.dev/docs/components/inputs/read_until
