### ISSUE TITLE
failed to decode private key while using tls client cert

### ISSUE THREAD

**Issue by abhisheks315** [benthosdev/benthos#1952]
I wrote a pipeline to stream data from kafka to opensearch. The opensearch cluster is tls protected so when I provide the tls configs opensearch (elasticsearch) I can get the pipeline to process messages successfully when I use the cert path. However when I use the client certs directly (https://www.benthos.dev/docs/components/outputs/elasticsearch/#tlsclient_certs) I get a `failed to decode private key` error

`ERRO Service closing due to: failed to init output <no label> path root.output: failed to decode private key  @service=benthos`

Its the same file contents that I'm using so why is it failing to decode the private key?

Update:
It works if I paste the contents of the certificate and key as a newline separated string but when I interpolate it by referencing it via env variables I get the above error again

**Comment by Jeffail** [comment]
Hey @abhisheks315, when there are newlines within the value it makes interpolating directly into the YAML config error prone as it could change the structure of the config. I'd recommend storing the value in a file and specifying it that way.
