### ISSUE TITLE
Query for Redis stuff

### ISSUE THREAD

**Issue by Shubh098** [benthosdev/benthos#1954]
HI,
i am running this config file , for pub sub key event notification .  
while in redis i am trying to set value using this :

 set namexyz '{"json": {"TrapId": "122", "NpuId": "0", "PacketDropped": 5, "PacketAccepted": 25},"ot":"1677690061.330262886"}'
OK

why am i not able to read up from the branch processor and write back to the original message?

benthos yaml :

input:
  redis_pubsub:
    url: redis://127.0.0.1:6379
    channels: ["__keyevent@0__:*"]  
    use_patterns: true
    
pipeline:
   processors:
     - branch:
        processors:  
          - redis:
              url: redis://127.0.0.1:6379 
              command: get
              #args_mapping: 'root = [ meta("namexyz") ]'
              args_mapping: root = this.namexyz
        result_map: root = this              
     - jq:
          query : '.'
output:
 stdout: {}
metrics:
  prometheus: {}
  mapping: ""
  
benthos-output:   
INFO Running main config from specified file       @service=benthos path=/nobackup/shutewar/Redis_input/test_Redis_list1.yaml
INFO Listening for HTTP requests at: http://0.0.0.0:4195  @service=benthos
ERRO HTTP Server error: listen tcp 0.0.0.0:4195: bind: address already in use  @service=benthos
INFO Launching a benthos instance, use CTRL+C to close  @service=benthos
INFO Receiving Redis pub/sub messages from channels: [__keyevent@0__:*]  @service=benthos label="" path=root.input
ERRO Branch error: processors failed: args mapping failed: failed assignment (line 1): unable to reference message as structured (with 'this.namexyz'): parse as json: invalid character 'a' in literal null (expecting 'u')  @service=benthos label="" path=root.pipeline.processors.0
namexyz

**Comment by ranaaditya** [comment]
@Jeffail @mihaitodor @mfamador @disintegrator ca anyone please help in this ?

Any leads will be helpful.

Thanks !

**Comment by Jeffail** [comment]
@ranaaditya please don't ping us directly, especially for questions. We're volunteering our time here.

**Comment by Shubh098** [comment]
HI @Jeffail 
 its seems , while on the input . it forwading only the key name i.e namexyz and when on the branch processor it received , it fails as not an json object. ideally i require with the key "namexyz" with its corresponding json object , that should be feeded to the pipeline  , is there a way ? 
 or second alternative -   with that key in the pipline how i can read the data using redis processor with the incoming key in the pipeline , and change the message with the current data holding with this key ? 
 tried lot from the documentation but unable to get much into , new to this benthos.

**Comment by Jeffail** [comment]
Oh I think I understand, sounds like you want your `args_mapping` to be set to the raw contents of the data received. Try:

```yaml
args_mapping: root = content().string()
```

**Comment by ranaaditya** [comment]
> @ranaaditya please don't ping us directly, especially for questions. We're volunteering our time here.

sorry @Jeffail for directly mentioning you. 

Thanks for the great work you are doing for opensource ❤️

**Comment by Shubh098** [comment]
i tried but ended with this :
ERRO Branch error: processors failed: invalid character 'a' in literal null (expecting 'u')  @service=benthos label="" path=root.pipeline.processors.0

let me more describe :
the objective i am trying is , the key ( "namexyz" ) which  feeded in the pipeline branch redis processor can with that key can i do. a get operation on that key , (that key is already set in the  redis with a json object) and the json object which comes from that key act as input to the other processor .

**Comment by mihaitodor** [comment]
Sounds like you need to write a short self-contained config which replicates the issue. Use a `generate` input and share something that we can run. Also, when prototyping bloblang stuff, you can use `benthos blobl server` to open a window in your browser and try out mappings with test data.

**Comment by Shubh098** [comment]
thanks @Jeffail and @mihaitodor , i tried this 
     - redis:
              url: redis://127.0.0.1:6379 
              command: get
              args_mapping: 'root = ["namexyz"]'       
     - jq:
        query: '. | fromjson '          
     - jq:
        query:  '{ "ot": .ot , "sum": (.json.PacketAccepted + .json.PacketDropped) }'

     - redis:
              url: redis://127.0.0.1:6379 
              command: set
              args_mapping: '["ott" , content().string() ]' 

its workingnow
