### ISSUE TITLE
Using custom plugin with Lambda and Benthos v4

### ISSUE THREAD

**Issue by sibest19** [benthosdev/benthos#1958]
Hello! Thank you for your contributions to Benthos!

I wanted to bring an issue to your attention regarding the usage of a Benthos custom plugin with Lambda and Benthos v4. I have developed a custom plugin and updated my `main.go` file to resemble the one found [here](https://github.com/benthosdev/benthos/blob/main/cmd/serverless/benthos-lambda/main.go), incorporating my plugin in the process.

My `main.go` looks like this:
```go
package main

import (
	_ "mymodule/plugins/processors"

	"github.com/benthosdev/benthos/v4/internal/serverless/lambda"

	// Import all plugins defined within the repo.
	_ "github.com/benthosdev/benthos/v4/public/components/all"
)

func main() {
	lambda.Run()
}

```

However, I have encountered an obstacle while attempting to build a binary with Lambda handlers. I am receiving an error message indicating that I am not permitted to import internal plugins.

I noticed that the `serverless-lambda` directory has been moved to an internal location. Could you kindly explain the rationale behind this change? Additionally, I was wondering if there is a solution available for the issue I am facing that doesn't involve forking Benthos' repo.

Thank you very much for your continued efforts, and please keep up the excellent work! 🙌

**Comment by germanozambelli** [comment]
You can use `github.com/benthosdev/benthos/v4/public/components/aws`, like this:
``` go
package main

import (
	"context"

	"github.com/benthosdev/benthos/v4/public/components/aws"

	_ "your-custom-plugin"
	_ "github.com/benthosdev/benthos/v4/public/components/all"
)

func main() {
	aws.RunLambda(context.Background())
}
```

**Comment by sibest19** [comment]
Hey! Thanks it worked perfectly. 🙌
