### ISSUE TITLE
Patching buffer stream component field does not work via REST API

### ISSUE THREAD

**Issue by imo-sice** [benthosdev/benthos#1966]
Hello!

We are trying to modify the buffer's `system_window` size value of a stream via REST API using the `PATCH` method. Even though the server returns a 200 code the configuration changes are not applied, and the log does not show any message (we have set the log level to `ALL`).

This is an example of how I am trying to do it:

```bash
curl --silent -vvv --show-error -X PATCH http://localhost:4195/streams/test -d '{"buffer":{"system_window":{"size":"60s"}}}'
```
Here is the server response:

```bash
*   Trying 127.0.0.1:4195...
* Connected to localhost (127.0.0.1) port 4195 (#0)
> PATCH /streams/test HTTP/1.1
> Host: localhost:4195
> User-Agent: curl/7.88.1
> Accept: */*
> Content-Length: 44
> Content-Type: application/x-www-form-urlencoded
> 
< HTTP/1.1 200 OK
< Date: Mon, 19 Jun 2023 10:06:06 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

The original window size was 30s, and after the 200 response we query the config status:

```bash
curl --silent --show-error -X GET http://localhost:4195/streams/test | jq '.config.buffer'
```

But the stream configuration remains the same (30s instead of the 60s we are trying to set)

```bash
{
  "system_window": {
    "size": "30s",
    "timestamp_mapping": "root = now()"
  }
}
```

We have also tried to `PATCH` the `input` component field without any trouble, working as expected in both configuration and log messages.

I'd like to know if there is some kind of restriction in modifying the `buffer` component, or if it could be a bug.

We are using the latest Benthos Docker image (`jeffail/benthos:4.17.0`)

Thank you and have a nice day!

**Comment by imo-sice** [comment]
@Jeffail thanks for the quick response! Glad to hear that the bug has already been located.

Sadly no, replacing the full stream configuration does not work for us. We are going to wait for the next release, but thanks!

Our use case is based on being able to update the value of the time window (through a web client), avoiding having to stop the server at any time. The config that we would have to store is too large and complex (the mapping part above all) to be saved in our database, but a JSON like `{"buffer":{"system_window":{"size":${window_size}}}}` is quite more feasible to store.

I've been studying the documentation, and it looks like streams `PATCH` method is the only way I've found to update values during runtime without restarting, as the environment variables are only loaded at container startup. 

I also tried to set the window size from the value of a key in the JSON we receive in Kafka with no luck (something like: `${! json("window_size") }'`), and also from a Kafka header (something like: `@window_size` or `meta("window_size")`) again with no luck.

If you could tell us if there is any other way to implement this use case I would appreciate it, but for the time being the PATCH approach could work for us.

Keep up the good work, and thank you!

P.S. Sorry for closing the issue...

**Comment by mihaitodor** [comment]
@imo-sice Were you able to test ecd4602 or are you still looking for a workaround until the next release is tagged? If you're running Benthos in Docker, you can use `jeffail/benthos:edge` to try it out, since it contains a binary built from the latest code on the `main` branch.

**Comment by imo-sice** [comment]
Hi @mihaitodor,

Yes, using `jeffail/benthos:edge` seems to solve the problem, however we will wait for the next fixed version (`4.17.1` or `4.18.0`) as we are in a pre production environment.

Any comments on whether you guys are to implement the `@ | meta` operator or `${! json("") }` to set the window time?

Thanks!

**Comment by Jeffail** [comment]
I'll hopefully get a release out this week or early next week, thanks for testing against `edge` @imo-sice!

**Comment by mihaitodor** [comment]
> Any comments on whether you guys are to implement the `@ | meta` operator or `${! json("") }` to set the window time?
> 
> Thanks!

Please open a separate issue for that as it’s unrelated to this one.
