### ISSUE TITLE
Use boblang independently

### ISSUE THREAD

**Issue by adpande** [benthosdev/benthos#1968]
Hi,

Boblang is such a terrific dsl that I want to use it even outside Benthios. Can embed the boblang parser executor directly in golang?

**Comment by mihaitodor** [comment]
Hey @adpande, indeed you can! See [here](https://pkg.go.dev/github.com/benthosdev/benthos/v4@v4.17.0/public/bloblang#example-package-BloblangRestrictedEnvironment) (and also [here](https://github.com/mihaitodor/benthos-playground/tree/main/wasm/blobl-editor)).
