### ISSUE TITLE
Bug: nats_jetstream input has a logic error in the bind check

### ISSUE THREAD

**Issue by RafalGoslawski** [benthosdev/benthos#1977]
In nats_jetstream input processor, I cannot use the `bind` option in combination with `subject` set, when the `stream` is empty.

According to this error message, either `durable` or `stream` is needed, but the check checks if any of the two is empty, instead of checking if both are empty.

https://github.com/benthosdev/benthos/blob/ecd46026bdf7eaf09bf0bf5b4a58b800e4ef6289/internal/impl/nats/input_jetstream.go#L176-L179

**Comment by Jeffail** [comment]
Whoops, thanks for raising this and making the fix quick, unfortunately you made it so easy I had it done before your PR was raised 😅 sorry: https://github.com/benthosdev/benthos/commit/85890950134def3c51140e938ed84be461d972d2
