### ISSUE TITLE
Pulsar Input doesn't allow using a pattern to select topics

### ISSUE THREAD

**Issue by treuherz** [benthosdev/benthos#1988]
Pulsar clients support consuming multiple topics dynamically by providing a regex (see [the `TopicsPattern` field](https://pkg.go.dev/github.com/apache/pulsar-client-go/pulsar#ConsumerOptions)) but the Benthos input config only supports providing an explicit list of topic names. We'd like to use Benthos for archiving jobs on large sets of topics, and would like to use the regex-subscription so we don't need to manually change the Benthos config when we create new topics.

I'd be happy to submit a PR for this - it looks very straightforward.

**Comment by Jeffail** [comment]
Hey @treuherz, sounds good, happy to have that added.
