### ISSUE TITLE
Bloblang support for zipping arrays

### ISSUE THREAD

**Issue by dudleycarr** [benthosdev/benthos#1991]
Zipping two arrays together is possible with `fold` but awkward.

**Comment by Jeffail** [comment]
Another way of doing this is to use enumerated: https://www.benthos.dev/docs/guides/bloblang/methods#enumerated:

```coffee
root.baz = this.foo.enumerated().map_each(iv -> [ iv.value, this.bar.index(iv.index) ])
```

However, that'd add a bunch of allocations that aren't really necessary as a `.zip` method would be straight forward to implement. I'll mark this as a good first issue but if no one picks it up then I'll do it in the next round of bloblang goodies.

If anyone wants to pick this up there are similar bloblang methods defined here to take inspiration from: https://github.com/benthosdev/benthos/blob/main/internal/impl/pure/bloblang_objects.go
