### ISSUE TITLE
Consider accepting schema in OLTP url

### ISSUE THREAD

**Issue by sananguliyev** [benthosdev/benthos#2001]
I have tried to send traces using open telemetry collector. It did not work as expected because I provided schema in the url. After checking the source code I noticed that benthos [uses hardcoded insecure mode](https://github.com/benthosdev/benthos/blob/main/internal/impl/otlp/tracer_otlp.go#L162-L164). Is it possible to make it configurable?

**Comment by sananguliyev** [comment]
There is a PR to solve this https://github.com/benthosdev/benthos/pull/2032. I will close this when that PR get merged.

**Comment by josephwoodward** [comment]
This issue can be closed now as #2032 has been merged.
