### ISSUE TITLE
AMQP_0_9 Optional Message Properties

### ISSUE THREAD

**Issue by thomas-tharp** [benthosdev/benthos#2009]
Hello,

I'm trying to figure out if there is a way to set any of the [optional message properties](https://www.rabbitmq.com/publishers.html#message-properties) when publishing via the AMQP 0.9 output. A few of them, like `type` and `content_type` appear to be supported as output config fields, but not all of them.

Specifically, my consumers rely heavily on the `message-id` field being populated by publishers. I've tried setting a metadata key named `message_id`, but it seems that metadata properties simply get passed through as message headers.

Any idea if this is possible - or if not, would you welcome a PR to try and implement this functionality?

**Comment by mihaitodor** [comment]
Hey @thomas-tharp, that sounds like something which should be added if the [underlying driver](https://github.com/rabbitmq/amqp091-go/) supports it. The current implementation is [here](https://github.com/benthosdev/benthos/blob/27f03a1ef59b50da33ffb237430f0f2d342d5333/internal/impl/amqp09/output.go#L355) and I see the `Publishing` struct has a [`MessageId` field](https://github.com/rabbitmq/amqp091-go/blob/77d6683c021ce14b73276d270e88f2f0e39c3cf7/types.go#L172) which Benthos isn't populating right now. Please feel fre to raise a PR

**Comment by zaeemarshad** [comment]
@thomas-tharp @mihaitodor I needed this as well. Here's the [PR](https://github.com/benthosdev/benthos/pull/2017). Please have a look.

**Comment by thomas-tharp** [comment]
@zaeemarshad This looks awesome! Exactly what I need.

**Comment by Jeffail** [comment]
Fixed: https://github.com/benthosdev/benthos/pull/2017
