### ISSUE TITLE
json arrays are merged by field values

### ISSUE THREAD

**Issue by gaoshenga** [benthosdev/benthos#2025]
json arrays are merged by primary key
```
{
"data1":[{"id":1,"tag1":"foo","tag2":"zoo"},{"id":2,"tag1":"foo","tag2":"zoo"},{"id":3,"tag1":"foo","tag2":"zoo"}],
"data2":[{"id":1,"tag3":"foo1","tag4":"zoo1"},{"id":2,"tag3":"foo1","tag4":"zoo1"},{"id":3,"tag3":"foo1","tag4":"zoo1"}]
}
```
Similar to the merging of an inner join and an outer join

Be combined into

```
{
"data":[{"id":1,"tag1":"foo","tag2":"zoo","tag3":"foo1","tag4":"zoo1"},{"id":2,"tag1":"foo","tag2":"zoo","tag3":"foo1","tag4":"zoo1"},{"id":3,"tag1":"foo","tag2":"zoo","tag3":"foo1","tag4":"zoo1"}]
}
```

How do you write a benthos configuration file like this?

**Comment by Jeffail** [comment]
Hey @gaoshenga, you'll likely want to use bloblang for this, the fold method is probably going to be needed: https://www.benthos.dev/docs/guides/bloblang/methods#fold, the best way to play around with mapping like this is to run `benthos blobl server`.

**Comment by gaoshenga** [comment]
@Jeffail The folding doesn't seem to work. I've already tried it. I want to merge two arrays, and the elements in the array are merged according to the primary key. Can you help me with some more methods or give me some examples?
It looks like this：
```
{
"data1":[{"id":1,"tag1":"foo","tag2":"zoo"},{"id":2,"tag1":"foo","tag2":"zoo"}],
"data2":[{"id":1,"tag3":"foo1"},{"id":2,"tag3":"foo1"}]
}
```
Merge according to the id in the object

```
{
"data":[{"id":1,"tag1":"foo","tag2":"zoo","tag3":"foo1"},{"id":2,"tag1":"foo","tag2":"zoo","tag3":"foo1"}]
}
```

**Comment by mihaitodor** [comment]
@gaoshenga Looks like you're trying to perform a join operation. This should do the trick:

```coffee
root = this.data1.map_each(i -> i.merge(data2.filter(j -> j.id == i.id).index(0).without("id").or({})))
```

Note that the above requires `O(n^2)` operations. If you're looking for an `O(n)` solution with `O(n)` extra memory, try this:

```coffee
let data2Map = this.data2.fold({}, i -> i.tally.merge({ i.value.id.string(): i.value.without("id") }))
root = this.data1.map_each(i -> i.merge($data2Map.get(i.id.string())))
```

Maybe there are better ways to do it, but I'm not an algorithm expert.
