### ISSUE TITLE
Option to skip linting for secret fields

### ISSUE THREAD

**Issue by pradeeppattamatta** [benthosdev/benthos#2057]
If we have some of the secrets injected into the config through environment variables, and the env variables are directly injected into the container at runtime, the linting at build time will fail. 

Can we have an option to skip linting specific fields or secret fields, similar to `--skip-env-var-check` option. If I use the `--skip-env-var-check` it will skip linting for all the env variables, and may not the ideal solution.

If this seems useful, I am open to looking at implementing it.

**Comment by Jeffail** [comment]
hey @pradeeppattamatta, if you specify env variables with defaults then they pass any linting, and that includes if the default is empty, so if a specific variable `${FOO}` is causing issues you can replace it with `${FOO:}` (anything after the colon is the default value, in this case an empty string).

**Comment by pradeeppattamatta** [comment]
Thanks @Jeffail. That works!
