### ISSUE TITLE
Option to read env files from a directory

### ISSUE THREAD

**Issue by pradeeppattamatta** [benthosdev/benthos#2062]
Today there is option to provide multiple env files with multiple `--env-file` arguments. Similar to the support to provide multiple resource files (`-r "./production/*.yaml" `), can we provide add support to provide multiple env files. 
This will be helpful in my case where I want to come up with common build scripts, where my internal clients can maintain their properties in multiple files in a directory and my scripts can be agnostic to those file names.

If this seems useful, I am open to looking at implementing it.

**Comment by Jeffail** [comment]
Hey @pradeeppattamatta, sounds like a good addition to add globs and super globs support, the change should be relatively straight forward as you can just copy the way that templates are expanded.

**Comment by pradeeppattamatta** [comment]
Thank @Jeffail. Will take a look and submit a PR.

**Comment by Jeffail** [comment]
Hey @pradeeppattamatta, I was in the area so implemented it just now: https://github.com/benthosdev/benthos/commit/9f574b892932977d038a45cba81ec212f76c8f70

**Comment by pradeeppattamatta** [comment]
Thank you @Jeffail
