### ISSUE TITLE
Elasticsearch output fails after 4.19.0 update

### ISSUE THREAD

**Issue by bn-sriramkannan** [benthosdev/benthos#2076]
Error message: 

```
elastic: Error 401 (Unauthorized): unable to authenticate user [redacted] for REST request [/_bulk] [type=security_exception]
```

**Comment by Jeffail** [comment]
Hey @bn-sriramkannan, thanks for raising this, it should be fixed with: https://github.com/benthosdev/benthos/commit/ec6611309995edd2fce6450ccc1980510fbef634, I'll try and get a release out shortly as this is a significant regression.

**Comment by Jeffail** [comment]
Fix is now released: https://github.com/benthosdev/benthos/releases/tag/v4.20.0
