### ISSUE TITLE
Possibility to set the number of partitions for new topics created by kafka output

### ISSUE THREAD

**Issue by DaruZero** [benthosdev/benthos#2088]
I would like to add the possibility to set the number of partitions for topics created by kafka output.

Let me explain my use case:
Our application runs on Kubernetes, where we have a Redpanda instance alongside multiple Benthos instances and other stuff. The problem with running Redpanda in k8s with Helm, is that one cannot set a default number of partitions for new topics (as seen in [this](https://github.com/redpanda-data/helm-charts/blob/af6c466e3d5e1a4d1fc366430bc97b0d445ae4c7/charts/redpanda/values.yaml#L940C20-L940C20) line).
In other components of our application we use the Sarama library to generate and manage consumers and producers, and it's possible to configure the number of partitions when creating a new kafka topic. Unfortunately, the data processed through Benthos does not come from or goes to any of those other components, therefore when producing new kafka topics from Benthos, Redpanda uses it's default value of 1 partition per topic.

It would be great to implement a `partitions` parameter that, if set, creates the new topic with the set number of partition, using the [`ClusterAdmin`](https://pkg.go.dev/github.com/Shopify/sarama@v1.38.1#ClusterAdmin) interface of sarama. It would also be possible to cache the topic names for increased speed. An example implementation can be seen in our sarama-wrapper, where in [this function](https://github.com/united-manufacturing-hub/Sarama-Kafka-Wrapper/blob/8f7f860c384b1afac4434d394b98f10af9a108f3/pkg/kafka/client.go#L254) we check if a topic exists and eventually create it before enqueueing the message (we use an async producer).
Of course, if the parameter is not set (or set to 0 maybe), then it would just not set the `NumPartitions` filed in the `sarama.TopicDetail` struct before creating the topic, thus using whatever default value is set in the kafka broker.

It would be nice to have some feedback about this functionality, and if it would be well received by the users, so that I could start working on the implementation.

**Comment by Jeffail** [comment]
Hey @DaruZero, I think that'd be generally nice to have. The topic is potentially dynamic as it's determined by interpolation functions, which means we can't determine the topic once at start up. That means whichever mechanism we use for customising topic creation needs to have a minimal impact on traffic.

**Comment by DaruZero** [comment]
Using a `syncmap` as cache we can check if the topic has already been created, and skip the topic creation process if that's the case.
Imho there are two options:
- use `ClusterAdmin.ListTopics()` at startup to prefetch all the existing topics and store them in cache. This can possibly slowing the startup if the broker has already many topics, but we can be sure that any topic not present in the cache is new and has to be created first
- only cache the topics coming in, being careful to check if `ClusterAdmin.CreateTopic()` returns a `TOPIC_ALREADY_EXISTS` error, in which case the topic can be cached and the message safely sent

**Comment by mapplechannel** [comment]
Hey @Jeffail ,When I connect to MySQL to read data, I find that int type and Boolean type data will be converted into string. Can I keep the original data type output?
The output of config.md is  
{"age":"5","gender":"0","name":"zhangsan"}
{"age":"8","gender":"1","name":"lisi"}

[config.md](https://github.com/benthosdev/benthos/files/12585396/config.md)
