### ISSUE TITLE
Input `redis_stream` enters busy loop on `xreadgroup` error

### ISSUE THREAD

**Issue by mattfysh** [benthosdev/benthos#2116]
Reproduction available here: https://github.com/mattfysh/bent_bug

when the XREADGROUP command fails, the benthos stream enters an infinite loop without a backoff. this causes a lot of pressure on the redis db.

**Comment by Jeffail** [comment]
Thanks for raising this @mattfysh, super helpful repro steps, got a fix here: https://github.com/benthosdev/benthos/commit/d46c9a56bf9a1ba4f979f1f807de3aa476b134c7
