### ISSUE TITLE
Cross-Site Scripting (XSS) at bloglang_editor_page.html

### ISSUE THREAD

**Issue by mariovr80** [benthosdev/benthos#2164]
The method .then embeds untrusted data in generated output with appendChild, at line 117 of benthos-main\internal\cli\blobl\resources\bloglang_editor_page.html. This untrusted data is embedded into the output without proper sanitization or encoding, enabling an attacker to inject malicious code into the generated web-page.

The attacker would be able to alter the returned web page by simply providing modified data in the user input response, which is read by the .then method at line 92 of benthos-main\internal\cli\blobl\resources\bloglang_editor_page.html. This input then flows through the code straight to the output web page, without sanitization. 

This can enable a Reflected Cross-Site Scripting (XSS) attack.

**Comment by Jeffail** [comment]
@mariovr80 can you clarify what you mean by "sanitization" in this case? The page is edited by adding a text node (`result = document.createTextNode(response.result);`) which as far as I understand it specifically prevents XSS attacks.
