### ISSUE TITLE
I have json array as result from a branch processor I'd like to run another processor based for each item of the result array without using output

### ISSUE THREAD

**Issue by jean-altura** [benthosdev/benthos#2167]
I have json array as result from a branch processor I'd like to run another processor based for each item of the result array without using output

**Comment by Jeffail** [comment]
@jean-altura use an unarchive processor with the format `json_array`: https://www.benthos.dev/docs/components/processors/unarchive.

Closing as per https://github.com/benthosdev/benthos/issues/2026
