### ISSUE TITLE
Whether kafka supports kerberos authentication

### ISSUE THREAD

**Issue by slivewo** [benthosdev/benthos#2175]

**Comment by mihaitodor** [comment]
I'm not very familiar with kerberos authentication, but it looks like there is [some support](https://github.com/linkedin/Burrow/issues/584) in the underlying library which the `kafka` input and output use. I guess those options can be exposed in the Benthos config, but it will require some investigation.

**Comment by mihaitodor** [comment]
Duplicate of #877
