### ISSUE TITLE
Website search results page always empty

### ISSUE THREAD

**Issue by mpartipilo** [benthosdev/benthos#2184]
The search box on the website shows me some results for the search terms, then clicking on the See all results takes me to e.g. https://www.benthos.dev/search/?q=duration and there are no results on that page. 

Searching for any other terms on that page also returns no results.

See: https://discord.com/channels/746368194196799589/746368194704572508/1166023124727377990

**Comment by mihaitodor** [comment]
Ugh, what a **PITA**. I think these 2 comments might help:

- https://github.com/facebook/docusaurus/issues/6693#issuecomment-1041545752
- https://github.com/facebook/docusaurus/issues/6693#issuecomment-1158639529

Basically, change `contextualSearch` to `true` [here](https://github.com/benthosdev/benthos/blob/9820711f2832637581996469fe64367c1bd5e583/website/docusaurus.config.js#L129), redeploy, delete the index in the Algolia dashboard, try to recreate it and ensure that it has the required attributes...
