### ISSUE TITLE
Schema_registry_encode subject not found when contains "/"

### ISSUE THREAD

**Issue by nrabe1010** [benthosdev/benthos#2190]
The `schema_registry_encode` processor with protobuf data cannot find schemas that include a `/` in the subject name. This affects all versions as far as I can tell. My guess is this is due to a bug with the subject name in the registry client request not being escaped properly.

```
level=error msg="schema subject 'proto/common/envelope.proto' not found by registry" @service=benthos label="" path=root.pipeline.processors.0
```
<img width="1487" alt="registrySubject" src="https://github.com/benthosdev/benthos/assets/22421773/19071fbc-6ea7-42b5-a53b-810f64c82ea2">

Here is a sample proto definitions I encountered this with. I can put together a gist of an example of this if requested.

(registered as `/proto/common/envelope.proto`)
```
syntax = "proto3";

package common;

message Envelope {
  string collectorId = 6;
}

```

(registered as product-value)
```
syntax = "proto3";

package raw;

import "proto/common/envelope.proto";

message Product {
  common.Envelope envelope = 1;
  optional uint64 aNumber = 2;
}
```

**Comment by Jeffail** [comment]
Hey @nrabe1010, thanks for the info, you're correct in that the subject URL paths were not being escaped. I've got a fix here: https://github.com/benthosdev/benthos/commit/7ae5fe618d1e0f501c3d61dfac63c67938d24667 which will be in the next release. If you get a chance to try it out with your use case please let me know how it goes.

**Comment by nrabe1010** [comment]
Thanks @Jeffail for the quick turnaround.

I was able to test this today and noticed the fix partially works. The referenced schema is not found, however, if I register two versions of the referenced `proto/common/envelope.proto` schema, one as is, and the other with a name as `proto%2Fcommon%2Fenvelope.proto`, Benthos is able to ser/de without issue.

**Comment by Jeffail** [comment]
Argh, thanks for testing @nrabe1010, I don't suppose there's a schema registry API spec that I can reference that you know of? If we're not meant to URL escape the subject then I'm not sure what it would expect us to do.

**Comment by nrabe1010** [comment]
I am not aware of one. I haven't been able to do too much digging into this, but did notice the following behavior:
```
curl -u admin:local-dev "http://127.0.0.1:30081/subjects/proto/common/envelope.proto/versions/latest"
# 404, definitely not an endpoint so this is expected

curl -u admin:local-dev "http://127.0.0.1:30081/subjects/proto%2Fcommon%2Fenvelope.proto/versions/latest"
# {"subject":"proto/common/envelope.proto" ...}
# working, expected

# What Benthos appears to be requesting
curl -u admin:local-dev "http://127.0.0.1:30081/subjects/proto%252Fcommon%252Fenvelope.proto/versions/latest"
# {"error_code":40401,"message":"Subject 'proto%2Fcommon%2Fenvelope.proto' not found."}
# This "works" if I register an additional schema w/ subject name including %2F
```

**Comment by Jeffail** [comment]
Ah okay so it's getting double escaped. I'll take another look before the next release.

**Comment by Jeffail** [comment]
Okay I found the issue: https://github.com/benthosdev/benthos/commit/9cc3a162fe5dfd41bb8293002c2b607671fe6b45, should be fixed in the next release.
