### ISSUE TITLE
why benthos install script needs sudo ?

### ISSUE THREAD

**Issue by setop** [benthosdev/benthos#2269]
https://github.com/benthosdev/benthos/blob/4da46671f378688023d24d28598b356ed395d41f/website/static/sh/install#L148

I want to install benthos in my user profile but I don't want the install script to require admin privileges.

I used asdf plugins, but in the end it invokes this script. I pressed CTRL+C.

Suggestion : check if install path is user owned, then ask use sudo if not.

**Comment by mihaitodor** [comment]
@setop Thank you for reporting this! I pushed a fix in #2270.
