### ISSUE TITLE
NATS KV Cache support

### ISSUE THREAD

**Issue by marshauf** [benthosdev/benthos#2280]
It would be nice to have NATS Jetstream KV bucket as a Cache Component. Teased in https://github.com/benthosdev/benthos/pull/1704#issuecomment-1443869635

It is possible to build a cache with the `nast_kv` processor, but requires more steps than to simply use a cache processor.

**Comment by mihaitodor** [comment]
Available since Benthos v4.27.0: https://www.benthos.dev/docs/components/caches/nats_kv
