### ISSUE TITLE
ERRO Connection lost due to: EOF 

### ISSUE THREAD

**Issue by GirishBhutiya** [benthosdev/benthos#2394]
I get `ERRO Connection lost due to: EOF                   @service=benthos label="" path=root.output stream=foo` error when stream multiple YAML files. just like explained at the below link.

https://www.benthos.dev/docs/guides/streams_mode/using_config_files

I have also posted it in detail in Stackoverflow. [here is the link.](https://stackoverflow.com/questions/78031917/erro-connection-lost-due-to-eof-benthos-stream)

**Comment by Jeffail** [comment]
Answered elsewhere: https://stackoverflow.com/questions/78031917/erro-connection-lost-due-to-eof-benthos-stream

Closing as per https://github.com/benthosdev/benthos/issues/2026

@GirishBhutiya in future please only ask questions in one place, as otherwise you're creating duplicate work for us.
