### ISSUE TITLE
No data consumed since update with 4.24.0 with batch_size at 1

### ISSUE THREAD

**Issue by tifennlegoff** [benthosdev/benthos#2401]
Hello,
We have recently update the Benthos version from 4.6.0 to 4.24.0. After this update, we observed that, for some of our pipelines, consumer showing as stable but just not processsing without any errors or warning on logs.

![benthos-not-consume](https://github.com/benthosdev/benthos/assets/25082085/841f3f58-95ff-4f28-9542-afb137f87554)

After enable log debug, we have messages about `Marking offset for topic` just before that Benthos stop processing but only for some partition, not for all. (The topic in question have 16 partitions)

```
time="2024-02-01T08:15:25Z" level=debug msg="Marking offset for topic 'xxxxxxxxxx-input' partition '7'." @service=benthos label="" path=root.input
```

We observe that all pipelines with is issue had `batch_size` at 1 (by default). We finally fix this issue by incrementing `batch_size` value from 1 to 5.

Since this modification, we don't observe this issue on our pipelines.

Maybe it's related with the new Samara update in [4.19.0](https://github.com/benthosdev/benthos/releases/tag/v4.19.0)

**Comment by Jeffail** [comment]
Hey @tifennlegoff would you mind testing with the latest release candidate (https://github.com/benthosdev/benthos/releases/tag/v4.25.0-rc2) with the `batch_size` to `1`. If the issue persists we'll need to take a look.

**Comment by tifennlegoff** [comment]
Hi @Jeffail ! Yes, no problems, I will trying to test it this week :+1:

**Comment by Jeffail** [comment]
@tifennlegoff thanks for confirming, looks like this has been fixed so closing.
