### ISSUE TITLE
"sql_insert" failed with ERROR ...too many parameters in Microsoft SQL server

### ISSUE THREAD

**Issue by JuliaPipson** [benthosdev/benthos#2424]
We tried to build benthos flow which read records from file and insert them into a table in Microsoft SQL server 2019,
We have used unarchive with json_array and then send it to output section:
"...
output:
  sql_insert:
    ...
"

We tried to use batching with sql_insert but it failed with or without this section.
ERROR:
The incoming request has too many parameters. The server supports a maximum of 2100 parameters

Our solution for now, was to use sql_raw, there we did insert query, one row each insert. But we know its not efficient way to do it DB (not insert in batch).

Is there a way to insert bulk/multiple rows and limit the max row in each insert ?

**Comment by Jeffail** [comment]
Hey @JuliaPipson, take a look at the split processor: https://www.benthos.dev/docs/components/processors/split, it allows you to break batches down into smaller sizes.

Closing as per: https://github.com/benthosdev/benthos/issues/2026
