### ISSUE TITLE
How to fail to exit

### ISSUE THREAD

**Issue by JuchangGit** [benthosdev/benthos#2426]
My config file demo10.yaml :

input:
  sql_raw:
    driver: "mysql" # No default (required)
    dsn: "root:rootpwd@tcp(127.0.0.1:3306)/ruoyi" # No default (required)
    query: SELECT user_id,user_name1 FROM sys_user; # No default (required)
buffer:
  none: {}
pipeline:
  threads: -1
  processors: []
output:
  stdout:
    codec: lines

Execute not terminate after error, how can I make it fail to exit with a failed state after an error ?
![image](https://github.com/benthosdev/benthos/assets/34911052/f15b30f0-330b-47c2-9ca3-99015f462c28)

**Comment by Jeffail** [comment]
Similar question has been answered here: https://github.com/benthosdev/benthos/discussions/2425

Closing as per https://github.com/benthosdev/benthos/issues/2026
