### ISSUE TITLE
Parsing custom structured JSON data as input

### ISSUE THREAD

**Issue by gregfurman** [benthosdev/benthos#2437]
Hi there! Busy familiarising myself with `Benthos` and `Bloblang` and am having loads of fun. I have a particular use-case though where I'd like some input on the approach.

### Problem
My data is loosely structured JSON and looks like:

```json
{
    "Species": "mackerel",
    "Count": "32"
}
{
    "Species": "herring",
    "Count": "87"
}
{
    "Species": "blobfish",
    "Count": "9001"
}
```

Because this is not correctly formatted as a JSON array, I use regex to read each object in the input. **This works to correctly parse the input**:

```yaml
input:
  stdin:
    scanner:
      re_match:
        pattern: '\{([^}]*)\}'

pipeline:
  processors:
   - mapping: root = this

output:
  stdout: {}
```

The data being formatted without the `\n` is **parsed without issue and does not require any regex matching**.

```json
{"Species": "mackerel", "Count": "32"}
{"Species": "herring","Count": "87"}
{"Species": "blobfish","Count": "9001"}
```

I am aware there are alternative approaches via `awk` and `jq` that can be used to format this in a more parse-friendly manner, but I am trying to take a fully `Benthos` approach to ingesting and streaming this data.

### Question
Am I missing something about how JSON input is parsed? I'd prefer not to use regex matching in favour of some other builtin functionality. Otherwise, is this a possible improvement that can be made to `Benthos'` JSON processing?.

Thanks again for this project! Looking forward to getting more involved in this ecosystem.

**Comment by Jeffail** [comment]
Hey @gregfurman if the data fits in memory you could consume it with the `to_the_end` codec and then use an unarchive processor with the format `json_documents`: https://www.benthos.dev/docs/components/processors/unarchive to expand it into a batch where each document is an individual message.

However, ideally we need to add a `json_documents` scanner type. It should be pretty straight forward as we can mostly copy from https://github.com/benthosdev/benthos/blob/main/internal/impl/pure/scanner_csv.go using a JSON decoder.

**Comment by gregfurman** [comment]
Ahh alright. Thanks for the response and info. I did explore `to_the_end` a bit but wasn't aware of the unarchive processor approach.  Happy to take on including a `json_documents`  scanner though -- seems like a good first issue.

**Comment by Jeffail** [comment]
@gregfurman that'd be great and yeah it's probably a good first issue. Let me know (here or discord) if you have any questions.
