### ISSUE TITLE
Comparing int64 values yields unexpected results

### ISSUE THREAD

**Issue by nicktelford** [benthosdev/benthos#2500]
When comparing large numbers coerced to `int64`, there appears to be some loss of precision in the comparison, yielding incorrect results.

Example:
```
$ echo '{}' | ./benthos blobl '1780921717355446273.int64() > 1780921717355446272.int64()'
false
```
Expected output:
```
true
```

**Comment by Jeffail** [comment]
Thanks for raising this @nicktelford, should be fixed with: https://github.com/benthosdev/benthos/commit/35e0b317b002b1f6197089b129e6aeae02608578

**Comment by nicktelford** [comment]
Thanks @Jeffail! Any idea when the next release will be cut?
