### ISSUE TITLE
can you add metrics.RegisterPlugin function?

### ISSUE THREAD

**Issue by jicanghaixb** [benthosdev/benthos#572]
hi:
   thanks for your benthos, now benthos supports add custom input/processor/manager/output/ratelimit/condition plugin.  I want control metrics function, can you support add custom metrics plugin?

**Comment by Jeffail** [comment]
Sorry, forgot to update this issue but we have a register API now: https://pkg.go.dev/github.com/benthosdev/benthos/v4@v4.3.0/public/service#RegisterMetricsExporter
