### ISSUE TITLE
Snowflake SQL Driver Option

### ISSUE THREAD

**Issue by nmbryant** [benthosdev/benthos#658]
Is there any interest in having Snowflake as a driver option in the SQL processor/output? The driver can be found here: https://github.com/snowflakedb/gosnowflake

**Comment by Jeffail** [comment]
Hey @nmbryant yes absolutely, any idea if there's a way to test it without using a snowflake account?

**Comment by nmbryant** [comment]
Unfortunately it doesn't seem like testing can be without an account from what I have found. I think adding the driver option would be a small change, should I just make the change without tests?

**Comment by ironchef** [comment]
Snowflake is pretty good with open source folks from what I've heard.  May be worth a shout out to someone like mpilman.  If not, I have access to snowflake and have used benthos in the past ... if I can swing some cycles I could potentially help.

**Comment by mihaitodor** [comment]
I'm exploring the library right now and trying to build an output. @ironchef do you have experience with the Snowflake platform? I'd love to have a chat with someone who can provide some feedback on how people expect this to work in practice, especially from a data streaming perspective.

**Comment by ironchef** [comment]
Yup yup .. mostly from a "hey .. execute this query and give me results" perspective on the golang side.  But I've integrated snowflake with AWS + S3, airflow, dbt, etc. (a bunch of other tooling).  I'll dm / email ya.

**Comment by mihaitodor** [comment]
Update: The `snowflake_put` output was merged in #1160. I think it's worth adding a corresponding input and, potentially, some alternatives based on `SELECT` / `INSERT`. Leaving this open for feedback.

**Comment by mihaitodor** [comment]
Closing this since, besides the existing `snowflake_put` output, Snowflake support was added to the various `sql_*` components in [v4.10.0](https://github.com/benthosdev/benthos/releases/tag/v4.10.0).
