### ISSUE TITLE
Kubernetes Configmap Directory Mount

### ISSUE THREAD

**Issue by kozelok** [benthosdev/benthos#671]
I've ran into an interesting issue with streams mode and "streams" directory mounted from a ConfigMap. 

This is a nice feature of kubernetes that lets me add an arbitrary number of files to ConfigMap and point benthos at it.
[DOCS](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-configmaps-from-directories)

Ran into a small issue where benthos follows the symlinks created and loads the files recursively until it encounters duplicates. https://github.com/Jeffail/benthos/blob/7b53fd8e0a82ef194ecabf883e963be051146f01/lib/service/service.go#L256
https://github.com/Jeffail/benthos/blob/7b53fd8e0a82ef194ecabf883e963be051146f01/lib/stream/manager/from_path.go#L69

One workaround I've found is the use Kubernetes subPath, which disables sym linking, but also means each file needs to be known ahead of time for volume mounts.

**Comment by kozelok** [comment]
Interesting that godoc says file path.Walk doesn't follow symlinks. 

https://golang.org/pkg/path/filepath/#Walk

**Comment by Jeffail** [comment]
Hey @kozelok, if I've understood correctly then we can solve this quite easily by supporting glob patterns in the streams arg, so you'd be able to do `benthos streams "./foo/*.yaml"`
