### ISSUE TITLE
Bloblang Question

### ISSUE THREAD

**Issue by zer0stars** [benthosdev/benthos#683]
I have a mapping question with Bloblang. Not sure if there is a simple way to accomplish this (programatically)

Given a json like this: 
`{
  "columns": ["col1","col2","col3" ],
  "values": [
     [234, 1,4,],
    [3,6,7 ]]
}`

How do I turn this into:
`{"col1":234, "col2":1, "col3":4}, {"col1":3, "col2":6, "col3":7}`

**Comment by yev-dimo** [comment]
Ive tired to use a for_each, but not sure how to get from columns by current index.

**Comment by Jeffail** [comment]
Hey @yev-dimo, looks like you want to use enumerated (https://www.benthos.dev/docs/guides/bloblang/methods#enumerated):

```
let columns = this.columns
root = this.values.map_each(
  this.enumerated().map_each({
    $columns.index(this.index): this.value,
  }).fold({}, this.tally.merge(this.value))
)
```

**Comment by ro971** [comment]
I am having two diiferent API, one API-1  is  giving the data "{"age":27,"dob":"1995-12-09T18:36:00.827Z","page":1}
" like this and API2 is giving the data like this "{"country":"England","region":"South Central"}
"  Now using benthos bloblang, I want to merge this two different data into one, How would I do this using benthos bloblang
"{"age":27,"dob":"1995-12-09T18:36:00.827Z","page":1}
"  "{"country":"England","region":"South Central"}
"

**Comment by mihaitodor** [comment]
@ro971 Try this:

```coffee
root = {"age":27,"dob":"1995-12-09T18:36:00.827Z","page":1}.merge({"country":"England","region":"South Central"})
```

In your case, I guess both objects are part of the current message, so then you'd do smth like this: `root = this.foo.merge(this.bar)`

**Comment by ro971** [comment]
Thanks.. @mihaitodor
