### ISSUE TITLE
Adding a connector

### ISSUE THREAD

**Issue by jmbnyc** [benthosdev/benthos#692]
Is there documentation on how to add a connector for input and output? I'd like to a connector for AMPS (www.crankuptheamps.com) but can't seem to find any documentation for how to get it done.

**Comment by iluminae** [comment]
@Jeffail wrote a post about making custom plugins [here](https://www.benthos.dev/blog/2019/08/19/write-a-benthos-plugin/) including an example repository. For anything bespoke that is probably the way to go.

**Comment by jmbnyc** [comment]
Thanks for your reply but I really do not want to write a plugin (or perhaps I just don't understand the terminology yet) but rather want to to write an "input" and "output" similar to other messaging systems. The "AMPS" protocol is very simple compared to most of the others that are already supported, e.g. it is 4 byte network order message length (excluding the 4 bytes), json header followed by payload which can be any message type.
Any pointers to code or any docs would be very helpful and appreciated.

**Comment by Jeffail** [comment]
Hey @jmbnyc, if you were to implement it as a plugin then the API is simpler and it would be easier for you to maintain it, there's a repo here with some example plugins: https://github.com/benthosdev/benthos-plugin-example which includes inputs and outputs. I'm currently in the process of building out a new plugin API which will make life even easier but it'll mostly the same interfaces.

If you go down the plugin approach your configuration files will look slightly different to a "native" Benthos input/output, something like this:

```yaml
input:
  type: foo
  plugin:
    field1: value1
    field2: value2
output:
  type: bar
  plugin:
    field1: value1
    field2: value2
```

However, you can also fork and add them natively, the APIs for this are also changing but mostly complete. I'm hoping to have a full contributors guide to adding new components eventually but for now the best option is to copy an existing one. A good example to work from would be the Pulsar connectors here: https://github.com/Jeffail/benthos/tree/master/internal/service/pulsar

**Comment by jmbnyc** [comment]
@Jeffail thanks for your response. I think I'll follow your advice and see where I can achieve. We already have a native go client for AMPS so it should not be too complicated. I appreciate the heads up on what is changing.
