### ISSUE TITLE
Avro binary input fails

### ISSUE THREAD

**Issue by KlausPopp** [benthosdev/benthos#763]
Hi,
I'm trying to inject binary avro format (generated with goavro lib BinaryFromNative) into the avro processor.
I get this error message 
`ervice":"benthos","component":"avro","level":"DEBUG","message":"Operator failed: failed to convert Avro document to JSON: cannot decode binary record \"my.namespace.com.indentity\" field \"FirstName\": cannot decode binary string: cannot decode binary bytes: negative size: -38"`.

When I use textual encoding (with TextualFromNative), everything works as expected.
Any hints?

**Comment by KlausPopp** [comment]
Sorry. Now that I've read the stdin documentation, it's clear. Stdin cannot know how long a binary avro message is. Sorry for disturbing you.

**Comment by Jeffail** [comment]
Hey @KlausPopp no worries, if you're piping a single message over `stdin` then you can configure it to gobble up the whole stream as a single message with the codec field:

```yaml
input:
  stdin:
    codec: all-bytes
```

Try that and see if it works, otherwise there might be some more digging to do.
