### ISSUE TITLE
Postgres insert doesn't work with a select

### ISSUE THREAD

**Issue by norcron** [benthosdev/benthos#767]
Hello! For a Postgres DB, I'm currently trying to build an insert with query that goes like this:

```
INSERT INTO public."Table1"("Username")
SELECT 'Username1'
FROM public."Table2" t2
WHERE t2."Username" = $1;
```

Just a vague example, don't really need the WHERE here, the thing is the insert doesn't work with the select, although I understand it can only execute one query at a time (cause apparently it might understand that those are 2 queries instead of 1) I was just wondering if it's possible in any way like this, I also understand I can just do 2 query processors separately and will work just fine.

Thank you very much!

**Comment by Jeffail** [comment]
Hey @norcron, unfortunately it's not possible to perform multiple queries in a single processor as the type of execution (insert versus select) determines how the query is executed and the results are aggregated. I doubt there's much we could do here to accommodate this, so using multiple processors would be the way to go.

**Comment by shaymanx** [comment]
Hey @nocron, I was able to get this to work within a SQL processor:
              query: "INSERT INTO public.table_2 SELECT * FROM public.table_1;"

The result is all of table_1's rows are now also in table_2.
