### ISSUE TITLE
Unexpected behaviour when assigning to variable

### ISSUE THREAD

**Issue by nikosgpet** [benthosdev/benthos#804]
If I assign a value to the root, the following works fine:

```
root = this.request
root.foo = 1
```

However, if I try the same thing with a variable, there is an error:

```
let var = this.request
$var.foo = 1
```
```
Error: failed to create pipeline: failed to create processor 'bloblang': line 2 char 1: expected import, map, or assignment
```

Ideally, this should be working the same way in both cases.

In my case I can't use root, because I need to do further processing by passing the value of $var into a function, and that's not possible with root at the moment. What is the best way to currently accomplish the assignment I am trying to do above using a variable?

**Comment by Jeffail** [comment]
Hey @nikosgpet, variables are can be reassigned with a new `let foo = bar` statement, but the contents themselves are immutable, which means you can't modify individual fields after the `let` statement. However, if you want to create a variable using a series of  assignments you can define a `map` that creates the structure and assign the result to a variable, so your example would become:

```coffee
map foo {
  root = this.request
  root.foo = 1
}

let var = this.apply("foo")
```

**Comment by Jeffail** [comment]
I've added a documentation tag as I'd like to make this more clear in the bloblang guide.

**Comment by nikosgpet** [comment]
Actually, this was a simplified version of what I was trying to accomplish. Any suggestions on how to accomplish the following?

```
let var = this.request
$var.foo = $bar
```

where `$bar` might be a variable that had to be computed or the result of a function. This doesn't currently seem possible with a map, because maps don't seem to interpret variables inside them.

**Comment by Jeffail** [comment]
Try something like this:

```coffee
map foo {
  root = this.request
  root.foo = this.bar
}

let var = {"request":this.request,"bar":$bar}.apply("foo")
```

Object (or array) literals are currently the only way to inject variables into a map. I'm considering adding proper variable definitions for maps but still not sure exactly how I want it to look.

**Comment by nikosgpet** [comment]
Thanks, that's a great solution! Much better than what I had in mind :)
