### ISSUE TITLE
Suggestion for maps

### ISSUE THREAD

**Issue by nikosgpet** [benthosdev/benthos#809]
I had a possible suggestion for maps that could be helpful, especially for long long repetitive maps.

I have a big json with hundreds of keys that I want to map to a smaller json, mapping about a dozen variables. Currently, in its simplest form the map needs to be declared as followed : 

```
map example {
  key1 = key1
  key2 = key2
  key3 = key3
  ...
  key100 = key100
}
```

It would be helpful if the simplest declaration we could make was: 
```
map example {
  key1
  key2
  key3 
  ...
  key100
}
```

The second form is more readable and easier to maintain. Each line translates to `root.keyX = this.keyX`

**Comment by Jeffail** [comment]
Hey @nikosgpet, the syntax looks neat but I'll need to think through whether the parser would introduce ambiguities. In the meantime you can probably tidy this up by using an array literal of your key names and using fold and merge to construct the object, it'd look like this:

```coffee
map example {
  root = [
    "key1",
    "key2",
    "key3",
    "key100",
  ].fold({}, item -> item.tally.merge({
    item.value: this.get(item.value)
  }))
}

root = this.apply("example")
```

**Comment by nikosgpet** [comment]
oh, that's neat, thanks!
