### ISSUE TITLE
Performance of streams mode

### ISSUE THREAD

**Issue by qiulin** [benthosdev/benthos#858]
I have dozens of tasks, just like input from kafka and output to db. Is there any difference between a benthos instance for each task and all tasks in a instance of streams mode?

**Comment by Jeffail** [comment]
Hey @qiulin, having all of your tasks executing in a single process does increase the contention for memory management so there is a possibility for the performance to be measurably slower. However, unless you're expecting exceptionally high throughput then I would expect the performance to be similar in streams mode versus individual instances, so if it's operationally simpler then I would advise going for it.

**Comment by qiulin** [comment]
Thank you, @Jeffail
