### ISSUE TITLE
Troubleshooting: Elasticsearch output connection issues?

### ISSUE THREAD

**Issue by klintan** [benthosdev/benthos#892]
Hello! 

So I guess I have two questions:
1.  My output config (very basic)
```
output:
  label: ""
  elasticsearch:
    urls:
      - http://localhost:9200
    index: ${ES_MENTIONED_INDEX:mentioned_index}
    action: index
    id: ${!json_field:id}
    type: document
    max_in_flight: 1
```
Started Elasticsearch locally in a docker
```
docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.15.0
```
And trying to index a document works well.

`curl -H "Content-Type: application/json" -XPOST "http://localhost:9200/test-index/12345" -d "{ \"test\" : \"value\"}"`

But running my pipeline I get this:
```
{"@timestamp":"2021-10-05T14:39:58-07:00","@service":"benthos","component":"benthos.output","level":"ERROR","message":"Failed to connect to elasticsearch: no active connection found: no Elasticsearch node available"}
```
But there are def nodes available:
```
curl -XGET 'http://localhost:9200/_nodes/http?pretty=true'


{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "docker-cluster",
  "nodes" : {
    "UnZpwe_xTk2GLM41FMeVww" : {
      "name" : "16edc8c8eecb",
      "transport_address" : "172.17.0.2:9300",
      "host" : "172.17.0.2",
      "ip" : "172.17.0.2",
      "version" : "7.15.0",
      "build_flavor" : "default",
      "build_type" : "docker",
      "build_hash" : "79d65f6e357953a5b3cbcc5e2c7c21073d89aa29",
      "roles" : [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_warm",
        "ingest",
        "master",
        "ml",
        "remote_cluster_client",
        "transform"
      ],
      "attributes" : {
        "ml.machine_memory" : "2081755136",
        "xpack.installed" : "true",
        "transform.node" : "true",
        "ml.max_open_jobs" : "512",
        "ml.max_jvm_size" : "1040187392"
      },
      "http" : {
        "bound_address" : [
          "0.0.0.0:9200"
        ],
        "publish_address" : "172.17.0.2:9200",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```

Any ideas on what this might be ? I was thinking host connection or similar, but I'm not running benthos in a docker so I don't think that should be an issue? Also tried both version 6 and 7 of ES, same issue with both.

2.
I tried `--log.level trace` and `log.level debug` but unfortunately they don't give much more information. Is there any way of getting more introspection into what is failing ? Seeing the raw request + responses that are sent for each step (processors + input + output)

Many thanks!
Let me know if I need to clarify or change anything.

**Comment by mihaitodor** [comment]
It looks like that error is triggered by [`sniff: true`](https://www.benthos.dev/docs/components/outputs/elasticsearch#sniff), which happens to be the default value. If you set `sniff: false` under `elasticsearch:` in your output config, it should work, just like [here](https://github.com/Jeffail/benthos/blob/4ae9b8b13d652bd918e788449eed4cdb08efb2ac/lib/test/integration/elasticsearch_test.go#L85). I'll do some digging on my end to see why this needs to be set to false when connecting to a single instance Elasticsearch node.

**Comment by Jeffail** [comment]
I need to read up more about sniffing as I've forgotten all the context but if this is likely to cause problems for others when enabled by default, and it doesn't weaken delivery guarantees or anything to disable it by default, then we can:

1. Make the field more prominent in the documentation so that it's clearer that it's a culprit for connectivity issues
2. Make a note to change it to `false` by default when we bump the major version to v4
