### ISSUE TITLE
Idea: publish Cue schemas and possibly support it natively

### ISSUE THREAD

**Issue by disintegrator** [benthosdev/benthos#920]
Hey, I've been playing with Benthos and, separately, [Cue](https://cuelang.org/) and having great time. I'm wondering if you think there's an opportunity to leverage a statically-typed configuration language such as Cue to describe Benthos primitives. Optionally, you can also accept `.cue` files (i.e. `benthos -r my_resources.cue -c my_config.cue`) though this is not strictly necessary. If the Cue team manages to deliver a good language server then I think the development experience will be great.

**Comment by Jeffail** [comment]
Hey @disintegrator! CUE has been on my radar for a little while. The config spec is entirely represented structurally in Go so we can already export representations like JSON schema, so with a bit of work I think it should be possible to do the same (perhaps even easier) for CUE.

I (believe) it'd be even easier to support importing a CUE config which is also something I'd like to get done, but in terms of what it enables us to do it's not as exciting, so I'd like to focus on generating the spec first.

**Comment by gedw99** [comment]
I am also using CueLang. Still getting into it.  

I wonder if anyone is thinking about replacing bloblang with CueLang.  The tooling and extensibility or Cue would tend to indicate its a winner. But i am sure there are some aspects of bloblang that Cue does not have too. Very curious about what other think.

**Comment by gedw99** [comment]
There is an autocomplete and lsp for Cue . I can’t remember where I saw it but it exists .

the Vscode for cue of course exists but I think an autocomplete for a golang based gui / ide is what the above issue maybe referring to

**Comment by gedw99** [comment]
Of course you get a cue fmt and cue vet and other tools that match the golang tools too

**Comment by disintegrator** [comment]
Resolved by #1199
