### ISSUE TITLE
protobuf: support for binary input `from_binary`

### ISSUE THREAD

**Issue by gunturaf** [benthosdev/benthos#961]
Hi there, I have a usecase for consuming Protobuf messages from Kafka and Kinesis but the Protobuf message is encoded as binary.

As we all know that there's already `from_json` operator for unmarshaling JSON as Protobuf message, with this issue I propose to add a new operator for unmarshaling directly from binary into Protobuf message, the operator name can be like `from_binary` or any other name.

I have a working prototype in my laptop (but I can't seems to run the integration test due to low end laptop), if this proposal is a-go then I can create PR right away.

**Comment by Jeffail** [comment]
Hey @gunturaf, do you mean marshal the message into a custom generated Go struct? If so I'm not sure we could generalize that within a processor, instead I'd recommend authoring a plugin (https://pkg.go.dev/github.com/Jeffail/benthos/v3/public/service) that benefits from the type safety of your custom generated proto code.

**Comment by gunturaf** [comment]
No, I mean the input from Kafka and Kinesis was in Protobuf binary format, not JSON, thus I need to convert it directly to a Protobuf message. This will behave just like `from_json`, but in my case the input was in binary. After that I can do further manipulation using `to_json` with Benthos the usual way.

So it looks like this: `(raw binary data) -> from_binary -> to_json -> other manipulations etc etc`

It's really just using `proto.Unmarshal` instead of `proto.UnmarshalJSON` similar in this line:
https://github.com/Jeffail/benthos/blob/2a78aa16a052c8af8cd81a570c5369dd3c05ba73/lib/processor/protobuf.go#L210

**Comment by gunturaf** [comment]
wait a moment... after a closer look, can I use `to_json` directly from binary input for this usecase?
