### ISSUE TITLE
Play with a WASM processor

### ISSUE THREAD

**Issue by Jeffail** [benthosdev/benthos#965]
We should do a bit of explorative work and see how easily a WASM processor using https://github.com/suborbital/reactr would be.

**Comment by gedw99** [comment]
tinygo was recently added, so it makes it much easier to test 👍 https://github.com/suborbital/reactr/tree/main/rwasm/testdata/tinygo-req

**Comment by iluminae** [comment]
I know that there are exec type extensibility for [inputs](https://www.benthos.dev/docs/components/inputs/subprocess), [processors](https://www.benthos.dev/docs/components/processors/subprocess), and [outputs](https://www.benthos.dev/docs/components/outputs/subprocess) but the contract for these things are more expressive than a fifo of bytes, as the stdin/stdout interface of subprocess is.

This would make the flexibility of benthos endless, and let orgs more comfortable in other languages be able to use benthos as a platform for their code with lower entry cost. The full interface exposed in the [public/service](https://github.com/benthosdev/benthos/tree/main/public/service) package can be exposed to the WASM implementation, and the WASM blob can be accessed from object store or whatever, which is a big advantage over building a go program to extend benthos.

Nothing new in this comment, just agreeing mostly. :)

**Comment by cortopy** [comment]
I'm also very interested in WASM. I come from a Rust and JS background, and being able to write a WASM plugin would just be ideal.

The bytecode alliance have just released v1 of [wasmtime](https://bytecodealliance.org/articles/wasmtime-1-0-fast-safe-and-production-ready), which will be a massive milestone for WASM and WASI. In a nutshell, startup time for a WASM invocation is now down to 5 microseconds.

There is a [wasmtime-go](https://github.com/bytecodealliance/wasmtime-go) package for easily embedding in a Go a program

**Comment by Jeffail** [comment]
Hey @cortopy, I forgot to update this ticket but there's an experimental WASI plugin implemented on this branch: https://github.com/benthosdev/benthos/tree/wasmtime-go, performance isn't amazing as we're having to pipe data to/from files but it's a starting point.

**Comment by cortopy** [comment]
thanks @Jeffail !!! That sounds amazing!!

**Comment by gedw99** [comment]
Cool stuff 

Which WASI runtime is used ??

**Comment by gedw99** [comment]
Ok it’s wasmtine. Was hoping it’s Wazero so there is zero cgo overhead / complications. 

https://github.com/tetratelabs/wazero

**Comment by Jeffail** [comment]
@gedw99 wazero is literally the next thing I'm going to try, will aim to have both to choose from.

**Comment by gedw99** [comment]
> @gedw99 wazero is literally the next thing I'm going to try, will aim to have both to choose from.

Also checkout Capsule that uses Wazero and NATS together . I was thinking of adding Benthos into that stack for all data transforms. 

All Actions are Sent to NATS works ( wasm ) and benthos does any data transform required via a NATS stream topic.
The mutated data goes back into NATS out of Benthos kicking off another Benthos WASM transform. 

You end up with a  Google sheets self hosted. You get parametric recursion just like Google Sheets.

**Comment by Jeffail** [comment]
Okay so I've put together a wasm processor using wazero so we still avoid the cgo dependencies: https://github.com/benthosdev/benthos/commit/da7179aefb1d7dd32dc34a7e7243adab73f8be28, I decided in the end to implement helper functions for accessing/mutating message data. We'll need to expand the exported functions and grow the number of language examples but the basics are there and ready to try.

Closing this issue for now as the experimentation is concluded.

**Comment by gedw99** [comment]
@Jeffail 
no CGO !!! that code looks really good.

if there is any examples ?  would love to have a play..

**Comment by mihaitodor** [comment]
@gedw99 Have a look here: https://github.com/benthosdev/benthos/tree/main/public/wasm I'm thinking to give Python a shot, but it looks like that might require some more work.

**Comment by gedw99** [comment]
thansk @mihaitodor will look now..

am glad i dont have to do python to wasm.. But would be interesting to see if its works.
