### ISSUE TITLE
Add new methods for spec

### ISSUE THREAD

**Issue by packman80** [benthosdev/benthos#974]
Adding NewInterpolatedStringListField() and NewInterpolatedStringMapField will be useful

**Comment by packman80** [comment]
thanks for @disintegrator, he closed **InterpolatedStringList** (https://github.com/benthosdev/benthos/pull/1550)

For "full house" we need InterpolatedStringMap also.

**Comment by disintegrator** [comment]
@packman80 glad that was helpful :)

[NewInterpolatedStringMapField](https://pkg.go.dev/github.com/benthosdev/benthos/v4@v4.6.0/public/service#NewInterpolatedStringMapField) and [FieldInterpolatedStringMap](https://pkg.go.dev/github.com/benthosdev/benthos/v4@v4.6.0/public/service#ParsedConfig.FieldInterpolatedStringMap) already existed. The list versions that I added were the missing pieces from what I gathered.

**Comment by packman80** [comment]
I missed it. Thank you! Closed issue
