### ISSUE TITLE
Bloblang dynamic property keys

### ISSUE THREAD

**Issue by Archanian** [benthosdev/benthos#996]
Heya, this is a question, I can't seem to find the answer in the docs so forgive me if I've missed it ...

Is it possible in a bloblang processor to set dynamic property keys? ie. something like:
```
root[this.AccountID] = this.UsageCount
```

**Comment by Jeffail** [comment]
Hey @Archanian yeah but the dynamic part needs to be on the query side of the expression, what I mean by that is you can't do `root[this.AccountID] = this.UsageCount`, but you _can_ do `root = { this.AccountID: this.UsageCount }` as object literals can have dynamic expressions as keys.

If your mapping is large and you want to keep it tidy then I'd suggest using a few tricks like custom maps and also the [`merge`](https://www.benthos.dev/docs/guides/bloblang/methods#merge) method. So if you were thinking of doing something like this:

```coffee
root.ID = uuid_v4()
root.User = this.Foo.User
root.UpdatedAt = now()
root[this.AccountID] = this.UsageCount
```

Then instead do this:

```coffee
# Normal style for most stuff
map main_fields {
  root.ID = uuid_v4()
  root.User = this.Foo.User
  root.UpdatedAt = now()
}

# Object literal style for dynamic stuff
map dynamic_fields {
  root = {
    this.AccountID: this.UsageCount
  }
}

root = this.apply("main_fields").merge(this.apply("dynamic_fields"))
```

**Comment by Archanian** [comment]
Awesome, thanks!
